/********************************************************************************
** Form generated from reading UI file 'fsc_mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FSC_MAINWINDOW_H
#define UI_FSC_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>
#include <qcustomplot.h>

QT_BEGIN_NAMESPACE

class Ui_FSC_MainWindow
{
public:
    QWidget *centralwidget;
    QToolButton *tbnSysDevCheck;
    QLabel *label;
    QComboBox *comboBox_SensorTypeName;
    QWidget *layoutWidget_2;
    QGridLayout *gridLayout_28;
    QLineEdit *leFlowSpeed_SensorSpan;
    QLabel *label_14;
    QSpacerItem *verticalSpacer_53;
    QSpacerItem *verticalSpacer_54;
    QSpacerItem *horizontalSpacer_33;
    QLabel *lbC_2;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QToolButton *tbnManualCheckDev;
    QToolButton *tbnCalStart;
    QFrame *line_4;
    QToolButton *tbnCalTermination;
    QTextBrowser *textBrow_calInfo;
    QLabel *label_16;
    QLineEdit *lineEdit_FM_1;
    QLineEdit *lineEdit_FM_2;
    QLineEdit *lineEdit_FM_4;
    QLineEdit *lineEdit_FM_3;
    QLineEdit *lineEdit_FM_6;
    QLineEdit *lineEdit_FM_5;
    QLineEdit *lineEdit_FM_8;
    QLineEdit *lineEdit_FM_7;
    QLineEdit *lineEdit_FM_11;
    QLineEdit *lineEdit_FM_10;
    QLineEdit *lineEdit_FM_12;
    QLineEdit *lineEdit_FM_9;
    QLineEdit *lineEdit_scale_show;
    QLineEdit *lineEdit_stdFM_sum;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *lineEdit_scale_flow;
    QLabel *label_19;
    QLabel *label_15;
    QLabel *label_22;
    QLineEdit *lineEdit_stdFM_flow;
    QLabel *label_23;
    QLabel *label_24;
    QCustomPlot *MyCustomPlot;
    QToolButton *tbnSensorType_5;
    QLineEdit *lineEdit_plotTime;
    QToolButton *tbnPoltClear;
    QGroupBox *groupBox;
    QComboBox *comboBox_PlotSenSel;
    QLabel *label_25;
    QFrame *line;
    QFrame *line_5;
    QLabel *label_12;
    QFrame *line_7;
    QGroupBox *groupBox_2;
    QLabel *label_13;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_45;
    QToolButton *tbnModifyFMTypePara;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLineEdit *leFMTypeName;
    QToolButton *tbnParaAdd;
    QToolButton *tbnParaErase;
    QFrame *line_2;
    QLabel *label_20;
    QLineEdit *lineEdit_FM_2_flow;
    QLineEdit *lineEdit_FM_10_flow;
    QLineEdit *lineEdit_FM_5_flow;
    QLineEdit *lineEdit_FM_3_flow;
    QLineEdit *lineEdit_FM_9_flow;
    QLineEdit *lineEdit_FM_8_flow;
    QLineEdit *lineEdit_FM_11_flow;
    QLineEdit *lineEdit_FM_12_flow;
    QLineEdit *lineEdit_FM_7_flow;
    QLineEdit *lineEdit_FM_6_flow;
    QLineEdit *lineEdit_FM_4_flow;
    QLineEdit *lineEdit_FM_1_flow;
    QToolButton *tbnScaleZero;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QPushButton *pushButton_debugReturn;
    QPushButton *pushButton_debugOff;
    QToolButton *tbnCalStepNext;
    QToolButton *tbnCalStepPre;
    QToolButton *tbnCalPause;
    QGroupBox *groupBox_3;
    QToolButton *tbnVOutClose;
    QToolButton *tbnPump1ForwardOff;
    QToolButton *tbnVForwardIn1Close;
    QToolButton *tbnPump1ForwardOn;
    QLineEdit *lineEdit_setPWM;
    QToolButton *tbnVReverseIn1Open;
    QToolButton *tbnVReverseIn2Open;
    QToolButton *tbnVForwardIn2Close;
    QToolButton *tbnVForwardIn2Open;
    QToolButton *tbnVReverseIn1Close;
    QLabel *label_26;
    QToolButton *tbnVReverseIn2Close;
    QLabel *label_21;
    QRadioButton *radioButton_setFlowRate;
    QRadioButton *radioButton_setPWM;
    QToolButton *tbnVOutOpen;
    QToolButton *tbnPump1ReverseOff;
    QToolButton *tbnPump1ReverseOn;
    QLineEdit *lineEdit_setFlowRate;
    QToolButton *tbnVForwardIn1Open;
    QToolButton *tbnPump2ReverseOn;
    QToolButton *tbnPump2ForwardOn;
    QToolButton *tbnPump2ForwardOff;
    QToolButton *tbnPump2ReverseOff;
    QLabel *label_90;
    QLabel *labelplcState;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *FSC_MainWindow)
    {
        if (FSC_MainWindow->objectName().isEmpty())
            FSC_MainWindow->setObjectName(QStringLiteral("FSC_MainWindow"));
        FSC_MainWindow->resize(1801, 923);
        centralwidget = new QWidget(FSC_MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        tbnSysDevCheck = new QToolButton(centralwidget);
        tbnSysDevCheck->setObjectName(QStringLiteral("tbnSysDevCheck"));
        tbnSysDevCheck->setGeometry(QRect(530, 820, 121, 21));
        label = new QLabel(centralwidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(55, 38, 141, 16));
        comboBox_SensorTypeName = new QComboBox(centralwidget);
        comboBox_SensorTypeName->setObjectName(QStringLiteral("comboBox_SensorTypeName"));
        comboBox_SensorTypeName->setEnabled(true);
        comboBox_SensorTypeName->setGeometry(QRect(54, 58, 171, 22));
        layoutWidget_2 = new QWidget(centralwidget);
        layoutWidget_2->setObjectName(QStringLiteral("layoutWidget_2"));
        layoutWidget_2->setGeometry(QRect(54, 87, 171, 34));
        gridLayout_28 = new QGridLayout(layoutWidget_2);
        gridLayout_28->setObjectName(QStringLiteral("gridLayout_28"));
        gridLayout_28->setContentsMargins(0, 0, 0, 0);
        leFlowSpeed_SensorSpan = new QLineEdit(layoutWidget_2);
        leFlowSpeed_SensorSpan->setObjectName(QStringLiteral("leFlowSpeed_SensorSpan"));
        leFlowSpeed_SensorSpan->setEnabled(true);
        leFlowSpeed_SensorSpan->setReadOnly(false);

        gridLayout_28->addWidget(leFlowSpeed_SensorSpan, 1, 2, 1, 1);

        label_14 = new QLabel(layoutWidget_2);
        label_14->setObjectName(QStringLiteral("label_14"));

        gridLayout_28->addWidget(label_14, 1, 3, 1, 1);

        verticalSpacer_53 = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        gridLayout_28->addItem(verticalSpacer_53, 0, 2, 1, 1);

        verticalSpacer_54 = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        gridLayout_28->addItem(verticalSpacer_54, 2, 2, 1, 1);

        horizontalSpacer_33 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        gridLayout_28->addItem(horizontalSpacer_33, 1, 1, 1, 1);

        lbC_2 = new QLabel(layoutWidget_2);
        lbC_2->setObjectName(QStringLiteral("lbC_2"));

        gridLayout_28->addWidget(lbC_2, 1, 0, 1, 1);

        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(53, 151, 31, 16));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(54, 191, 41, 16));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(54, 227, 41, 16));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(54, 264, 41, 16));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(54, 301, 41, 16));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(54, 321, 41, 16));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(54, 170, 41, 16));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(54, 209, 41, 16));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(54, 245, 41, 16));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(54, 282, 41, 16));
        tbnManualCheckDev = new QToolButton(centralwidget);
        tbnManualCheckDev->setObjectName(QStringLiteral("tbnManualCheckDev"));
        tbnManualCheckDev->setGeometry(QRect(660, 820, 71, 21));
        tbnCalStart = new QToolButton(centralwidget);
        tbnCalStart->setObjectName(QStringLiteral("tbnCalStart"));
        tbnCalStart->setGeometry(QRect(312, 43, 51, 81));
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(274, 786, 1327, 90));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        tbnCalTermination = new QToolButton(centralwidget);
        tbnCalTermination->setObjectName(QStringLiteral("tbnCalTermination"));
        tbnCalTermination->setGeometry(QRect(1182, 43, 51, 81));
        textBrow_calInfo = new QTextBrowser(centralwidget);
        textBrow_calInfo->setObjectName(QStringLiteral("textBrow_calInfo"));
        textBrow_calInfo->setGeometry(QRect(372, 43, 801, 81));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(382, 208, 111, 16));
        lineEdit_FM_1 = new QLineEdit(centralwidget);
        lineEdit_FM_1->setObjectName(QStringLiteral("lineEdit_FM_1"));
        lineEdit_FM_1->setEnabled(false);
        lineEdit_FM_1->setGeometry(QRect(492, 208, 71, 20));
        lineEdit_FM_1->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_1->setReadOnly(true);
        lineEdit_FM_2 = new QLineEdit(centralwidget);
        lineEdit_FM_2->setObjectName(QStringLiteral("lineEdit_FM_2"));
        lineEdit_FM_2->setEnabled(true);
        lineEdit_FM_2->setGeometry(QRect(572, 208, 71, 20));
        lineEdit_FM_2->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_2->setReadOnly(true);
        lineEdit_FM_4 = new QLineEdit(centralwidget);
        lineEdit_FM_4->setObjectName(QStringLiteral("lineEdit_FM_4"));
        lineEdit_FM_4->setEnabled(true);
        lineEdit_FM_4->setGeometry(QRect(732, 208, 71, 20));
        lineEdit_FM_4->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_4->setReadOnly(true);
        lineEdit_FM_3 = new QLineEdit(centralwidget);
        lineEdit_FM_3->setObjectName(QStringLiteral("lineEdit_FM_3"));
        lineEdit_FM_3->setEnabled(true);
        lineEdit_FM_3->setGeometry(QRect(652, 208, 71, 20));
        lineEdit_FM_3->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_3->setReadOnly(true);
        lineEdit_FM_6 = new QLineEdit(centralwidget);
        lineEdit_FM_6->setObjectName(QStringLiteral("lineEdit_FM_6"));
        lineEdit_FM_6->setEnabled(true);
        lineEdit_FM_6->setGeometry(QRect(892, 208, 71, 20));
        lineEdit_FM_6->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_6->setReadOnly(true);
        lineEdit_FM_5 = new QLineEdit(centralwidget);
        lineEdit_FM_5->setObjectName(QStringLiteral("lineEdit_FM_5"));
        lineEdit_FM_5->setEnabled(true);
        lineEdit_FM_5->setGeometry(QRect(812, 208, 71, 20));
        lineEdit_FM_5->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_5->setReadOnly(true);
        lineEdit_FM_8 = new QLineEdit(centralwidget);
        lineEdit_FM_8->setObjectName(QStringLiteral("lineEdit_FM_8"));
        lineEdit_FM_8->setEnabled(true);
        lineEdit_FM_8->setGeometry(QRect(1094, 207, 71, 20));
        lineEdit_FM_8->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_8->setReadOnly(true);
        lineEdit_FM_7 = new QLineEdit(centralwidget);
        lineEdit_FM_7->setObjectName(QStringLiteral("lineEdit_FM_7"));
        lineEdit_FM_7->setEnabled(true);
        lineEdit_FM_7->setGeometry(QRect(1014, 207, 71, 20));
        lineEdit_FM_7->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_7->setReadOnly(true);
        lineEdit_FM_11 = new QLineEdit(centralwidget);
        lineEdit_FM_11->setObjectName(QStringLiteral("lineEdit_FM_11"));
        lineEdit_FM_11->setEnabled(true);
        lineEdit_FM_11->setGeometry(QRect(1334, 207, 71, 20));
        lineEdit_FM_11->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_11->setReadOnly(true);
        lineEdit_FM_10 = new QLineEdit(centralwidget);
        lineEdit_FM_10->setObjectName(QStringLiteral("lineEdit_FM_10"));
        lineEdit_FM_10->setEnabled(true);
        lineEdit_FM_10->setGeometry(QRect(1254, 207, 71, 20));
        lineEdit_FM_10->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_10->setReadOnly(true);
        lineEdit_FM_12 = new QLineEdit(centralwidget);
        lineEdit_FM_12->setObjectName(QStringLiteral("lineEdit_FM_12"));
        lineEdit_FM_12->setEnabled(true);
        lineEdit_FM_12->setGeometry(QRect(1414, 207, 71, 20));
        lineEdit_FM_12->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_12->setReadOnly(true);
        lineEdit_FM_9 = new QLineEdit(centralwidget);
        lineEdit_FM_9->setObjectName(QStringLiteral("lineEdit_FM_9"));
        lineEdit_FM_9->setEnabled(true);
        lineEdit_FM_9->setGeometry(QRect(1174, 207, 71, 20));
        lineEdit_FM_9->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_9->setReadOnly(true);
        lineEdit_scale_show = new QLineEdit(centralwidget);
        lineEdit_scale_show->setObjectName(QStringLiteral("lineEdit_scale_show"));
        lineEdit_scale_show->setEnabled(false);
        lineEdit_scale_show->setGeometry(QRect(482, 142, 101, 20));
        lineEdit_scale_show->setLayoutDirection(Qt::LeftToRight);
        lineEdit_scale_show->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_scale_show->setReadOnly(true);
        lineEdit_stdFM_sum = new QLineEdit(centralwidget);
        lineEdit_stdFM_sum->setObjectName(QStringLiteral("lineEdit_stdFM_sum"));
        lineEdit_stdFM_sum->setEnabled(false);
        lineEdit_stdFM_sum->setGeometry(QRect(482, 167, 101, 20));
        lineEdit_stdFM_sum->setLayoutDirection(Qt::LeftToRight);
        lineEdit_stdFM_sum->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_stdFM_sum->setReadOnly(true);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(652, 170, 101, 16));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(382, 145, 61, 16));
        lineEdit_scale_flow = new QLineEdit(centralwidget);
        lineEdit_scale_flow->setObjectName(QStringLiteral("lineEdit_scale_flow"));
        lineEdit_scale_flow->setEnabled(false);
        lineEdit_scale_flow->setGeometry(QRect(752, 143, 101, 20));
        lineEdit_scale_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_scale_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_scale_flow->setReadOnly(true);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(652, 145, 81, 16));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(862, 143, 36, 20));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(862, 168, 36, 20));
        lineEdit_stdFM_flow = new QLineEdit(centralwidget);
        lineEdit_stdFM_flow->setObjectName(QStringLiteral("lineEdit_stdFM_flow"));
        lineEdit_stdFM_flow->setEnabled(false);
        lineEdit_stdFM_flow->setGeometry(QRect(752, 167, 101, 20));
        lineEdit_stdFM_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_stdFM_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_stdFM_flow->setReadOnly(true);
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(592, 168, 36, 20));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(382, 170, 121, 16));
        MyCustomPlot = new QCustomPlot(centralwidget);
        MyCustomPlot->setObjectName(QStringLiteral("MyCustomPlot"));
        MyCustomPlot->setGeometry(QRect(302, 280, 1271, 531));
        tbnSensorType_5 = new QToolButton(MyCustomPlot);
        tbnSensorType_5->setObjectName(QStringLiteral("tbnSensorType_5"));
        tbnSensorType_5->setGeometry(QRect(0, 510, 111, 21));
        lineEdit_plotTime = new QLineEdit(MyCustomPlot);
        lineEdit_plotTime->setObjectName(QStringLiteral("lineEdit_plotTime"));
        lineEdit_plotTime->setEnabled(true);
        lineEdit_plotTime->setGeometry(QRect(1110, 510, 51, 20));
        lineEdit_plotTime->setLayoutDirection(Qt::LeftToRight);
        lineEdit_plotTime->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_plotTime->setReadOnly(true);
        tbnPoltClear = new QToolButton(MyCustomPlot);
        tbnPoltClear->setObjectName(QStringLiteral("tbnPoltClear"));
        tbnPoltClear->setGeometry(QRect(1040, 510, 61, 21));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(292, 260, 1291, 561));
        comboBox_PlotSenSel = new QComboBox(centralwidget);
        comboBox_PlotSenSel->setObjectName(QStringLiteral("comboBox_PlotSenSel"));
        comboBox_PlotSenSel->setGeometry(QRect(1375, 255, 111, 22));
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(592, 143, 36, 20));
        line = new QFrame(centralwidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(265, 19, 20, 811));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(276, -20, 371, 80));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(672, 10, 141, 16));
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(742, -20, 861, 80));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(25, 20, 231, 446));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(58, 108, 31, 16));
        label_31 = new QLabel(groupBox_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(29, 108, 31, 16));
        label_32 = new QLabel(groupBox_2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(72, 322, 51, 16));
        label_45 = new QLabel(groupBox_2);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(154, 322, 51, 16));
        tbnModifyFMTypePara = new QToolButton(groupBox_2);
        tbnModifyFMTypePara->setObjectName(QStringLiteral("tbnModifyFMTypePara"));
        tbnModifyFMTypePara->setGeometry(QRect(29, 341, 171, 21));
        label_29 = new QLabel(groupBox_2);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(85, 108, 31, 16));
        label_30 = new QLabel(groupBox_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(111, 108, 31, 16));
        label_54 = new QLabel(groupBox_2);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(193, 108, 31, 16));
        label_55 = new QLabel(groupBox_2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(140, 108, 31, 16));
        label_56 = new QLabel(groupBox_2);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(167, 108, 31, 16));
        leFMTypeName = new QLineEdit(groupBox_2);
        leFMTypeName->setObjectName(QStringLiteral("leFMTypeName"));
        leFMTypeName->setEnabled(true);
        leFMTypeName->setGeometry(QRect(70, 381, 131, 20));
        leFMTypeName->setReadOnly(false);
        tbnParaAdd = new QToolButton(groupBox_2);
        tbnParaAdd->setObjectName(QStringLiteral("tbnParaAdd"));
        tbnParaAdd->setGeometry(QRect(30, 402, 91, 21));
        tbnParaErase = new QToolButton(groupBox_2);
        tbnParaErase->setObjectName(QStringLiteral("tbnParaErase"));
        tbnParaErase->setGeometry(QRect(120, 402, 81, 21));
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(1592, 19, 20, 812));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(382, 230, 111, 16));
        lineEdit_FM_2_flow = new QLineEdit(centralwidget);
        lineEdit_FM_2_flow->setObjectName(QStringLiteral("lineEdit_FM_2_flow"));
        lineEdit_FM_2_flow->setEnabled(true);
        lineEdit_FM_2_flow->setGeometry(QRect(572, 230, 71, 20));
        lineEdit_FM_2_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_2_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_2_flow->setReadOnly(true);
        lineEdit_FM_10_flow = new QLineEdit(centralwidget);
        lineEdit_FM_10_flow->setObjectName(QStringLiteral("lineEdit_FM_10_flow"));
        lineEdit_FM_10_flow->setEnabled(true);
        lineEdit_FM_10_flow->setGeometry(QRect(1254, 229, 71, 20));
        lineEdit_FM_10_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_10_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_10_flow->setReadOnly(true);
        lineEdit_FM_5_flow = new QLineEdit(centralwidget);
        lineEdit_FM_5_flow->setObjectName(QStringLiteral("lineEdit_FM_5_flow"));
        lineEdit_FM_5_flow->setEnabled(true);
        lineEdit_FM_5_flow->setGeometry(QRect(812, 230, 71, 20));
        lineEdit_FM_5_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_5_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_5_flow->setReadOnly(true);
        lineEdit_FM_3_flow = new QLineEdit(centralwidget);
        lineEdit_FM_3_flow->setObjectName(QStringLiteral("lineEdit_FM_3_flow"));
        lineEdit_FM_3_flow->setEnabled(true);
        lineEdit_FM_3_flow->setGeometry(QRect(652, 230, 71, 20));
        lineEdit_FM_3_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_3_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_3_flow->setReadOnly(true);
        lineEdit_FM_9_flow = new QLineEdit(centralwidget);
        lineEdit_FM_9_flow->setObjectName(QStringLiteral("lineEdit_FM_9_flow"));
        lineEdit_FM_9_flow->setEnabled(true);
        lineEdit_FM_9_flow->setGeometry(QRect(1174, 229, 71, 20));
        lineEdit_FM_9_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_9_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_9_flow->setReadOnly(true);
        lineEdit_FM_8_flow = new QLineEdit(centralwidget);
        lineEdit_FM_8_flow->setObjectName(QStringLiteral("lineEdit_FM_8_flow"));
        lineEdit_FM_8_flow->setEnabled(true);
        lineEdit_FM_8_flow->setGeometry(QRect(1094, 229, 71, 20));
        lineEdit_FM_8_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_8_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_8_flow->setReadOnly(true);
        lineEdit_FM_11_flow = new QLineEdit(centralwidget);
        lineEdit_FM_11_flow->setObjectName(QStringLiteral("lineEdit_FM_11_flow"));
        lineEdit_FM_11_flow->setEnabled(true);
        lineEdit_FM_11_flow->setGeometry(QRect(1334, 229, 71, 20));
        lineEdit_FM_11_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_11_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_11_flow->setReadOnly(true);
        lineEdit_FM_12_flow = new QLineEdit(centralwidget);
        lineEdit_FM_12_flow->setObjectName(QStringLiteral("lineEdit_FM_12_flow"));
        lineEdit_FM_12_flow->setEnabled(true);
        lineEdit_FM_12_flow->setGeometry(QRect(1414, 229, 71, 20));
        lineEdit_FM_12_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_12_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_12_flow->setReadOnly(true);
        lineEdit_FM_7_flow = new QLineEdit(centralwidget);
        lineEdit_FM_7_flow->setObjectName(QStringLiteral("lineEdit_FM_7_flow"));
        lineEdit_FM_7_flow->setEnabled(true);
        lineEdit_FM_7_flow->setGeometry(QRect(1014, 229, 71, 20));
        lineEdit_FM_7_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_7_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_7_flow->setReadOnly(true);
        lineEdit_FM_6_flow = new QLineEdit(centralwidget);
        lineEdit_FM_6_flow->setObjectName(QStringLiteral("lineEdit_FM_6_flow"));
        lineEdit_FM_6_flow->setEnabled(true);
        lineEdit_FM_6_flow->setGeometry(QRect(892, 230, 71, 20));
        lineEdit_FM_6_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_6_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_6_flow->setReadOnly(true);
        lineEdit_FM_4_flow = new QLineEdit(centralwidget);
        lineEdit_FM_4_flow->setObjectName(QStringLiteral("lineEdit_FM_4_flow"));
        lineEdit_FM_4_flow->setEnabled(true);
        lineEdit_FM_4_flow->setGeometry(QRect(732, 230, 71, 20));
        lineEdit_FM_4_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_4_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_4_flow->setReadOnly(true);
        lineEdit_FM_1_flow = new QLineEdit(centralwidget);
        lineEdit_FM_1_flow->setObjectName(QStringLiteral("lineEdit_FM_1_flow"));
        lineEdit_FM_1_flow->setEnabled(false);
        lineEdit_FM_1_flow->setGeometry(QRect(492, 230, 71, 20));
        lineEdit_FM_1_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_1_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_1_flow->setReadOnly(true);
        tbnScaleZero = new QToolButton(centralwidget);
        tbnScaleZero->setObjectName(QStringLiteral("tbnScaleZero"));
        tbnScaleZero->setGeometry(QRect(920, 143, 91, 21));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(1741, 74, 18, 16));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(1741, 103, 30, 16));
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(1741, 162, 16, 16));
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(1740, 220, 16, 16));
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(1740, 190, 16, 16));
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(1740, 250, 16, 16));
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(1740, 280, 16, 16));
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(1740, 310, 16, 16));
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(1740, 340, 16, 16));
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(1740, 366, 16, 16));
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(1740, 393, 16, 16));
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(1740, 420, 16, 16));
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(1740, 450, 16, 16));
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(1740, 480, 16, 16));
        pushButton_debugReturn = new QPushButton(centralwidget);
        pushButton_debugReturn->setObjectName(QStringLiteral("pushButton_debugReturn"));
        pushButton_debugReturn->setGeometry(QRect(1680, 810, 75, 23));
        pushButton_debugOff = new QPushButton(centralwidget);
        pushButton_debugOff->setObjectName(QStringLiteral("pushButton_debugOff"));
        pushButton_debugOff->setGeometry(QRect(1680, 580, 75, 23));
        tbnCalStepNext = new QToolButton(centralwidget);
        tbnCalStepNext->setObjectName(QStringLiteral("tbnCalStepNext"));
        tbnCalStepNext->setGeometry(QRect(1299, 44, 51, 81));
        tbnCalStepPre = new QToolButton(centralwidget);
        tbnCalStepPre->setObjectName(QStringLiteral("tbnCalStepPre"));
        tbnCalStepPre->setGeometry(QRect(1353, 44, 51, 81));
        tbnCalPause = new QToolButton(centralwidget);
        tbnCalPause->setObjectName(QStringLiteral("tbnCalPause"));
        tbnCalPause->setGeometry(QRect(1236, 44, 51, 81));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(25, 480, 231, 351));
        tbnVOutClose = new QToolButton(groupBox_3);
        tbnVOutClose->setObjectName(QStringLiteral("tbnVOutClose"));
        tbnVOutClose->setGeometry(QRect(124, 24, 91, 21));
        tbnPump1ForwardOff = new QToolButton(groupBox_3);
        tbnPump1ForwardOff->setObjectName(QStringLiteral("tbnPump1ForwardOff"));
        tbnPump1ForwardOff->setGeometry(QRect(124, 227, 91, 21));
        tbnVForwardIn1Close = new QToolButton(groupBox_3);
        tbnVForwardIn1Close->setObjectName(QStringLiteral("tbnVForwardIn1Close"));
        tbnVForwardIn1Close->setGeometry(QRect(124, 59, 91, 21));
        tbnPump1ForwardOn = new QToolButton(groupBox_3);
        tbnPump1ForwardOn->setObjectName(QStringLiteral("tbnPump1ForwardOn"));
        tbnPump1ForwardOn->setGeometry(QRect(16, 227, 91, 21));
        lineEdit_setPWM = new QLineEdit(groupBox_3);
        lineEdit_setPWM->setObjectName(QStringLiteral("lineEdit_setPWM"));
        lineEdit_setPWM->setEnabled(true);
        lineEdit_setPWM->setGeometry(QRect(133, 178, 61, 20));
        lineEdit_setPWM->setLayoutDirection(Qt::LeftToRight);
        lineEdit_setPWM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_setPWM->setReadOnly(false);
        tbnVReverseIn1Open = new QToolButton(groupBox_3);
        tbnVReverseIn1Open->setObjectName(QStringLiteral("tbnVReverseIn1Open"));
        tbnVReverseIn1Open->setGeometry(QRect(18, 117, 91, 21));
        tbnVReverseIn2Open = new QToolButton(groupBox_3);
        tbnVReverseIn2Open->setObjectName(QStringLiteral("tbnVReverseIn2Open"));
        tbnVReverseIn2Open->setGeometry(QRect(18, 139, 91, 21));
        tbnVForwardIn2Close = new QToolButton(groupBox_3);
        tbnVForwardIn2Close->setObjectName(QStringLiteral("tbnVForwardIn2Close"));
        tbnVForwardIn2Close->setGeometry(QRect(124, 82, 91, 21));
        tbnVForwardIn2Open = new QToolButton(groupBox_3);
        tbnVForwardIn2Open->setObjectName(QStringLiteral("tbnVForwardIn2Open"));
        tbnVForwardIn2Open->setGeometry(QRect(18, 82, 91, 21));
        tbnVReverseIn1Close = new QToolButton(groupBox_3);
        tbnVReverseIn1Close->setObjectName(QStringLiteral("tbnVReverseIn1Close"));
        tbnVReverseIn1Close->setGeometry(QRect(124, 117, 91, 21));
        label_26 = new QLabel(groupBox_3);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(197, 176, 36, 20));
        QFont font;
        font.setFamily(QStringLiteral("AcadEref"));
        font.setPointSize(12);
        label_26->setFont(font);
        tbnVReverseIn2Close = new QToolButton(groupBox_3);
        tbnVReverseIn2Close->setObjectName(QStringLiteral("tbnVReverseIn2Close"));
        tbnVReverseIn2Close->setGeometry(QRect(124, 139, 91, 21));
        label_21 = new QLabel(groupBox_3);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(87, 177, 36, 20));
        radioButton_setFlowRate = new QRadioButton(groupBox_3);
        radioButton_setFlowRate->setObjectName(QStringLiteral("radioButton_setFlowRate"));
        radioButton_setFlowRate->setGeometry(QRect(23, 204, 89, 16));
        radioButton_setFlowRate->setChecked(true);
        radioButton_setPWM = new QRadioButton(groupBox_3);
        radioButton_setPWM->setObjectName(QStringLiteral("radioButton_setPWM"));
        radioButton_setPWM->setGeometry(QRect(133, 204, 89, 16));
        tbnVOutOpen = new QToolButton(groupBox_3);
        tbnVOutOpen->setObjectName(QStringLiteral("tbnVOutOpen"));
        tbnVOutOpen->setGeometry(QRect(18, 24, 91, 21));
        tbnPump1ReverseOff = new QToolButton(groupBox_3);
        tbnPump1ReverseOff->setObjectName(QStringLiteral("tbnPump1ReverseOff"));
        tbnPump1ReverseOff->setGeometry(QRect(124, 249, 91, 21));
        tbnPump1ReverseOn = new QToolButton(groupBox_3);
        tbnPump1ReverseOn->setObjectName(QStringLiteral("tbnPump1ReverseOn"));
        tbnPump1ReverseOn->setGeometry(QRect(16, 249, 91, 21));
        lineEdit_setFlowRate = new QLineEdit(groupBox_3);
        lineEdit_setFlowRate->setObjectName(QStringLiteral("lineEdit_setFlowRate"));
        lineEdit_setFlowRate->setEnabled(true);
        lineEdit_setFlowRate->setGeometry(QRect(23, 178, 61, 20));
        lineEdit_setFlowRate->setLayoutDirection(Qt::LeftToRight);
        lineEdit_setFlowRate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_setFlowRate->setReadOnly(false);
        tbnVForwardIn1Open = new QToolButton(groupBox_3);
        tbnVForwardIn1Open->setObjectName(QStringLiteral("tbnVForwardIn1Open"));
        tbnVForwardIn1Open->setGeometry(QRect(18, 59, 91, 21));
        tbnPump2ReverseOn = new QToolButton(groupBox_3);
        tbnPump2ReverseOn->setObjectName(QStringLiteral("tbnPump2ReverseOn"));
        tbnPump2ReverseOn->setGeometry(QRect(16, 307, 91, 21));
        tbnPump2ForwardOn = new QToolButton(groupBox_3);
        tbnPump2ForwardOn->setObjectName(QStringLiteral("tbnPump2ForwardOn"));
        tbnPump2ForwardOn->setGeometry(QRect(16, 285, 91, 21));
        tbnPump2ForwardOff = new QToolButton(groupBox_3);
        tbnPump2ForwardOff->setObjectName(QStringLiteral("tbnPump2ForwardOff"));
        tbnPump2ForwardOff->setGeometry(QRect(124, 285, 91, 21));
        tbnPump2ReverseOff = new QToolButton(groupBox_3);
        tbnPump2ReverseOff->setObjectName(QStringLiteral("tbnPump2ReverseOff"));
        tbnPump2ReverseOff->setGeometry(QRect(124, 307, 91, 21));
        label_90 = new QLabel(centralwidget);
        label_90->setObjectName(QStringLiteral("label_90"));
        label_90->setGeometry(QRect(60, 402, 41, 16));
        labelplcState = new QLabel(centralwidget);
        labelplcState->setObjectName(QStringLiteral("labelplcState"));
        labelplcState->setGeometry(QRect(1670, 50, 101, 16));
        FSC_MainWindow->setCentralWidget(centralwidget);
        groupBox_2->raise();
        line_4->raise();
        groupBox->raise();
        MyCustomPlot->raise();
        line_2->raise();
        line_7->raise();
        line_5->raise();
        tbnSysDevCheck->raise();
        label->raise();
        comboBox_SensorTypeName->raise();
        layoutWidget_2->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        tbnManualCheckDev->raise();
        tbnCalStart->raise();
        tbnCalTermination->raise();
        textBrow_calInfo->raise();
        label_16->raise();
        lineEdit_FM_1->raise();
        lineEdit_FM_2->raise();
        lineEdit_FM_4->raise();
        lineEdit_FM_3->raise();
        lineEdit_FM_6->raise();
        lineEdit_FM_5->raise();
        lineEdit_FM_8->raise();
        lineEdit_FM_7->raise();
        lineEdit_FM_11->raise();
        lineEdit_FM_10->raise();
        lineEdit_FM_12->raise();
        lineEdit_FM_9->raise();
        lineEdit_scale_show->raise();
        lineEdit_stdFM_sum->raise();
        label_17->raise();
        label_18->raise();
        lineEdit_scale_flow->raise();
        label_19->raise();
        label_15->raise();
        label_22->raise();
        lineEdit_stdFM_flow->raise();
        label_23->raise();
        label_24->raise();
        comboBox_PlotSenSel->raise();
        label_25->raise();
        line->raise();
        label_12->raise();
        label_20->raise();
        lineEdit_FM_2_flow->raise();
        lineEdit_FM_10_flow->raise();
        lineEdit_FM_5_flow->raise();
        lineEdit_FM_3_flow->raise();
        lineEdit_FM_9_flow->raise();
        lineEdit_FM_8_flow->raise();
        lineEdit_FM_11_flow->raise();
        lineEdit_FM_12_flow->raise();
        lineEdit_FM_7_flow->raise();
        lineEdit_FM_6_flow->raise();
        lineEdit_FM_4_flow->raise();
        lineEdit_FM_1_flow->raise();
        tbnScaleZero->raise();
        label_27->raise();
        label_28->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        pushButton_debugReturn->raise();
        pushButton_debugOff->raise();
        tbnCalStepNext->raise();
        tbnCalStepPre->raise();
        tbnCalPause->raise();
        groupBox_3->raise();
        label_90->raise();
        labelplcState->raise();
        menubar = new QMenuBar(FSC_MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1801, 23));
        FSC_MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(FSC_MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        FSC_MainWindow->setStatusBar(statusbar);
        QWidget::setTabOrder(tbnSysDevCheck, leFlowSpeed_SensorSpan);
        QWidget::setTabOrder(leFlowSpeed_SensorSpan, comboBox_SensorTypeName);
        QWidget::setTabOrder(comboBox_SensorTypeName, tbnManualCheckDev);
        QWidget::setTabOrder(tbnManualCheckDev, tbnCalStart);
        QWidget::setTabOrder(tbnCalStart, tbnCalTermination);
        QWidget::setTabOrder(tbnCalTermination, textBrow_calInfo);
        QWidget::setTabOrder(textBrow_calInfo, lineEdit_FM_1);
        QWidget::setTabOrder(lineEdit_FM_1, lineEdit_FM_2);
        QWidget::setTabOrder(lineEdit_FM_2, lineEdit_FM_4);
        QWidget::setTabOrder(lineEdit_FM_4, lineEdit_FM_3);
        QWidget::setTabOrder(lineEdit_FM_3, lineEdit_FM_6);
        QWidget::setTabOrder(lineEdit_FM_6, lineEdit_FM_5);
        QWidget::setTabOrder(lineEdit_FM_5, lineEdit_FM_8);
        QWidget::setTabOrder(lineEdit_FM_8, lineEdit_FM_7);
        QWidget::setTabOrder(lineEdit_FM_7, lineEdit_FM_11);
        QWidget::setTabOrder(lineEdit_FM_11, lineEdit_FM_10);
        QWidget::setTabOrder(lineEdit_FM_10, lineEdit_FM_12);
        QWidget::setTabOrder(lineEdit_FM_12, lineEdit_FM_9);
        QWidget::setTabOrder(lineEdit_FM_9, lineEdit_scale_show);
        QWidget::setTabOrder(lineEdit_scale_show, lineEdit_stdFM_sum);
        QWidget::setTabOrder(lineEdit_stdFM_sum, lineEdit_scale_flow);
        QWidget::setTabOrder(lineEdit_scale_flow, lineEdit_stdFM_flow);
        QWidget::setTabOrder(lineEdit_stdFM_flow, tbnSensorType_5);
        QWidget::setTabOrder(tbnSensorType_5, lineEdit_plotTime);
        QWidget::setTabOrder(lineEdit_plotTime, tbnPoltClear);
        QWidget::setTabOrder(tbnPoltClear, comboBox_PlotSenSel);
        QWidget::setTabOrder(comboBox_PlotSenSel, tbnVOutOpen);
        QWidget::setTabOrder(tbnVOutOpen, tbnPump1ForwardOn);
        QWidget::setTabOrder(tbnPump1ForwardOn, tbnPump1ReverseOn);
        QWidget::setTabOrder(tbnPump1ReverseOn, tbnPump1ForwardOff);
        QWidget::setTabOrder(tbnPump1ForwardOff, tbnVOutClose);
        QWidget::setTabOrder(tbnVOutClose, tbnPump1ReverseOff);
        QWidget::setTabOrder(tbnPump1ReverseOff, tbnVForwardIn2Open);
        QWidget::setTabOrder(tbnVForwardIn2Open, tbnVForwardIn1Open);
        QWidget::setTabOrder(tbnVForwardIn1Open, tbnVReverseIn1Open);
        QWidget::setTabOrder(tbnVReverseIn1Open, tbnVReverseIn2Open);
        QWidget::setTabOrder(tbnVReverseIn2Open, tbnVForwardIn2Close);
        QWidget::setTabOrder(tbnVForwardIn2Close, tbnVForwardIn1Close);
        QWidget::setTabOrder(tbnVForwardIn1Close, tbnVReverseIn1Close);
        QWidget::setTabOrder(tbnVReverseIn1Close, tbnVReverseIn2Close);
        QWidget::setTabOrder(tbnVReverseIn2Close, lineEdit_setFlowRate);
        QWidget::setTabOrder(lineEdit_setFlowRate, lineEdit_setPWM);
        QWidget::setTabOrder(lineEdit_setPWM, radioButton_setFlowRate);
        QWidget::setTabOrder(radioButton_setFlowRate, radioButton_setPWM);
        QWidget::setTabOrder(radioButton_setPWM, lineEdit_FM_2_flow);
        QWidget::setTabOrder(lineEdit_FM_2_flow, lineEdit_FM_10_flow);
        QWidget::setTabOrder(lineEdit_FM_10_flow, lineEdit_FM_5_flow);
        QWidget::setTabOrder(lineEdit_FM_5_flow, lineEdit_FM_3_flow);
        QWidget::setTabOrder(lineEdit_FM_3_flow, lineEdit_FM_9_flow);
        QWidget::setTabOrder(lineEdit_FM_9_flow, lineEdit_FM_8_flow);
        QWidget::setTabOrder(lineEdit_FM_8_flow, lineEdit_FM_11_flow);
        QWidget::setTabOrder(lineEdit_FM_11_flow, lineEdit_FM_12_flow);
        QWidget::setTabOrder(lineEdit_FM_12_flow, lineEdit_FM_7_flow);
        QWidget::setTabOrder(lineEdit_FM_7_flow, lineEdit_FM_6_flow);
        QWidget::setTabOrder(lineEdit_FM_6_flow, lineEdit_FM_4_flow);
        QWidget::setTabOrder(lineEdit_FM_4_flow, lineEdit_FM_1_flow);
        QWidget::setTabOrder(lineEdit_FM_1_flow, tbnScaleZero);

        retranslateUi(FSC_MainWindow);

        QMetaObject::connectSlotsByName(FSC_MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *FSC_MainWindow)
    {
        FSC_MainWindow->setWindowTitle(QApplication::translate("FSC_MainWindow", "\346\265\201\351\207\217\344\274\240\346\204\237\345\231\250\346\240\207\345\256\232\350\275\257\344\273\266", Q_NULLPTR));
        tbnSysDevCheck->setText(QApplication::translate("FSC_MainWindow", "\350\207\252\345\212\250\346\243\200\346\237\245\347\263\273\347\273\237\350\256\276\345\244\207", Q_NULLPTR));
        label->setText(QApplication::translate("FSC_MainWindow", "\351\200\211\346\213\251\345\276\205\346\240\207\345\256\232\344\274\240\346\204\237\345\231\250\345\236\213\345\217\267\357\274\232", Q_NULLPTR));
        label_14->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        lbC_2->setText(QApplication::translate("FSC_MainWindow", "\351\207\217\347\250\213\357\274\232", Q_NULLPTR));
        label_2->setText(QApplication::translate("FSC_MainWindow", "100%\357\274\232", Q_NULLPTR));
        label_3->setText(QApplication::translate("FSC_MainWindow", "80%\357\274\232", Q_NULLPTR));
        label_4->setText(QApplication::translate("FSC_MainWindow", "60%\357\274\232", Q_NULLPTR));
        label_5->setText(QApplication::translate("FSC_MainWindow", "40%\357\274\232", Q_NULLPTR));
        label_6->setText(QApplication::translate("FSC_MainWindow", "20%\357\274\232", Q_NULLPTR));
        label_7->setText(QApplication::translate("FSC_MainWindow", "10%\357\274\232", Q_NULLPTR));
        label_8->setText(QApplication::translate("FSC_MainWindow", "90%\357\274\232", Q_NULLPTR));
        label_9->setText(QApplication::translate("FSC_MainWindow", "70%\357\274\232", Q_NULLPTR));
        label_10->setText(QApplication::translate("FSC_MainWindow", "50%\357\274\232", Q_NULLPTR));
        label_11->setText(QApplication::translate("FSC_MainWindow", "30%\357\274\232", Q_NULLPTR));
        tbnManualCheckDev->setText(QApplication::translate("FSC_MainWindow", "\346\211\213\345\212\250\346\243\200\346\237\245", Q_NULLPTR));
        tbnCalStart->setText(QApplication::translate("FSC_MainWindow", "\345\274\200\345\247\213", Q_NULLPTR));
        tbnCalTermination->setText(QApplication::translate("FSC_MainWindow", "\347\273\210\346\255\242", Q_NULLPTR));
        textBrow_calInfo->setHtml(QApplication::translate("FSC_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", Q_NULLPTR));
        label_16->setText(QApplication::translate("FSC_MainWindow", "\345\276\205\346\240\207\345\256\232\344\274\240\346\204\237\345\231\250\347\264\257\350\256\241\357\274\232", Q_NULLPTR));
        lineEdit_FM_1->setText(QApplication::translate("FSC_MainWindow", "-22100.123", Q_NULLPTR));
        lineEdit_FM_2->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_4->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_3->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_6->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_5->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_8->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_7->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_11->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_10->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_12->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_9->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_scale_show->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_stdFM_sum->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        label_17->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\207\206\346\265\201\351\207\217\350\256\241\346\265\201\351\207\217\357\274\232", Q_NULLPTR));
        label_18->setText(QApplication::translate("FSC_MainWindow", "\345\244\251\345\271\263\346\230\276\347\244\272\357\274\232", Q_NULLPTR));
        lineEdit_scale_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        label_19->setText(QApplication::translate("FSC_MainWindow", "\345\244\251\345\271\263\350\256\241\347\256\227\346\265\201\351\200\237\357\274\232", Q_NULLPTR));
        label_15->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        label_22->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        lineEdit_stdFM_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        label_23->setText(QApplication::translate("FSC_MainWindow", "ml", Q_NULLPTR));
        label_24->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\207\206\346\265\201\351\207\217\350\256\241\347\264\257\350\256\241\357\274\232", Q_NULLPTR));
        tbnSensorType_5->setText(QApplication::translate("FSC_MainWindow", "\346\237\245\347\234\213\346\240\207\345\256\232\346\212\245\345\221\212", Q_NULLPTR));
        lineEdit_plotTime->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        tbnPoltClear->setText(QApplication::translate("FSC_MainWindow", "\346\270\205\347\251\272", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("FSC_MainWindow", "\345\217\230\345\214\226\346\233\262\347\272\277", Q_NULLPTR));
        comboBox_PlotSenSel->clear();
        comboBox_PlotSenSel->insertItems(0, QStringList()
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2501", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2502", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2503", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2504", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2505", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2506", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2507", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2508", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2509", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\25010", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\25011", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\25012", Q_NULLPTR)
        );
        label_25->setText(QApplication::translate("FSC_MainWindow", "ml", Q_NULLPTR));
        label_12->setText(QApplication::translate("FSC_MainWindow", "\350\207\252\345\212\250\346\240\207\345\256\232", Q_NULLPTR));
        groupBox_2->setTitle(QString());
        label_13->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\256\232", Q_NULLPTR));
        label_31->setText(QApplication::translate("FSC_MainWindow", "\351\207\217\347\250\213", Q_NULLPTR));
        label_32->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221", Q_NULLPTR));
        label_45->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221", Q_NULLPTR));
        tbnModifyFMTypePara->setText(QApplication::translate("FSC_MainWindow", "\344\277\256\346\224\271\347\241\256\350\256\244", Q_NULLPTR));
        label_29->setText(QApplication::translate("FSC_MainWindow", "\351\252\214\350\257\201", Q_NULLPTR));
        label_30->setText(QApplication::translate("FSC_MainWindow", "\344\277\256\346\255\243", Q_NULLPTR));
        label_54->setText(QApplication::translate("FSC_MainWindow", "\344\277\256\346\255\243", Q_NULLPTR));
        label_55->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\256\232", Q_NULLPTR));
        label_56->setText(QApplication::translate("FSC_MainWindow", "\351\252\214\350\257\201", Q_NULLPTR));
        tbnParaAdd->setText(QApplication::translate("FSC_MainWindow", "\346\267\273\345\212\240", Q_NULLPTR));
        tbnParaErase->setText(QApplication::translate("FSC_MainWindow", "\345\210\240\351\231\244", Q_NULLPTR));
        label_20->setText(QApplication::translate("FSC_MainWindow", "\345\276\205\346\240\207\345\256\232\344\274\240\346\204\237\345\231\250\346\265\201\351\207\217\357\274\232", Q_NULLPTR));
        lineEdit_FM_2_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_10_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_5_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_3_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_9_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_8_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_11_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_12_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_7_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_6_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_4_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_1_flow->setText(QApplication::translate("FSC_MainWindow", "-22100.123", Q_NULLPTR));
        tbnScaleZero->setText(QApplication::translate("FSC_MainWindow", "\345\216\273\347\232\256\346\270\205\351\233\266", Q_NULLPTR));
        label_27->setText(QApplication::translate("FSC_MainWindow", "plc", Q_NULLPTR));
        label_28->setText(QApplication::translate("FSC_MainWindow", "scale", Q_NULLPTR));
        label_33->setText(QApplication::translate("FSC_MainWindow", "1#", Q_NULLPTR));
        label_34->setText(QApplication::translate("FSC_MainWindow", "3#", Q_NULLPTR));
        label_35->setText(QApplication::translate("FSC_MainWindow", "2#", Q_NULLPTR));
        label_36->setText(QApplication::translate("FSC_MainWindow", "4#", Q_NULLPTR));
        label_37->setText(QApplication::translate("FSC_MainWindow", "5#", Q_NULLPTR));
        label_38->setText(QApplication::translate("FSC_MainWindow", "6#", Q_NULLPTR));
        label_39->setText(QApplication::translate("FSC_MainWindow", "7#", Q_NULLPTR));
        label_40->setText(QApplication::translate("FSC_MainWindow", "8#", Q_NULLPTR));
        label_41->setText(QApplication::translate("FSC_MainWindow", "9#", Q_NULLPTR));
        label_42->setText(QApplication::translate("FSC_MainWindow", "10#", Q_NULLPTR));
        label_43->setText(QApplication::translate("FSC_MainWindow", "11#", Q_NULLPTR));
        label_44->setText(QApplication::translate("FSC_MainWindow", "12#", Q_NULLPTR));
        pushButton_debugReturn->setText(QApplication::translate("FSC_MainWindow", "return", Q_NULLPTR));
        pushButton_debugOff->setText(QApplication::translate("FSC_MainWindow", "stop all", Q_NULLPTR));
        tbnCalStepNext->setText(QApplication::translate("FSC_MainWindow", "\344\270\213\344\270\200\346\255\245", Q_NULLPTR));
        tbnCalStepPre->setText(QApplication::translate("FSC_MainWindow", "\344\270\212\344\270\200\346\255\245", Q_NULLPTR));
        tbnCalPause->setText(QApplication::translate("FSC_MainWindow", "\346\232\202\345\201\234", Q_NULLPTR));
        groupBox_3->setTitle(QString());
        tbnVOutClose->setText(QApplication::translate("FSC_MainWindow", "\346\224\276\346\260\264\351\230\200\345\205\263", Q_NULLPTR));
        tbnPump1ForwardOff->setText(QApplication::translate("FSC_MainWindow", "1#\346\263\265\346\255\243\350\277\233\346\260\264\345\201\234\346\255\242", Q_NULLPTR));
        tbnVForwardIn1Close->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2001\345\205\263", Q_NULLPTR));
        tbnPump1ForwardOn->setText(QApplication::translate("FSC_MainWindow", "1#\346\263\265\346\255\243\350\277\233\346\260\264\345\220\257\345\212\250", Q_NULLPTR));
        lineEdit_setPWM->setText(QApplication::translate("FSC_MainWindow", "0", Q_NULLPTR));
        tbnVReverseIn1Open->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2001\345\274\200", Q_NULLPTR));
        tbnVReverseIn2Open->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2002\345\274\200", Q_NULLPTR));
        tbnVForwardIn2Close->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2002\345\205\263", Q_NULLPTR));
        tbnVForwardIn2Open->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2002\345\274\200", Q_NULLPTR));
        tbnVReverseIn1Close->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2001\345\205\263", Q_NULLPTR));
        label_26->setText(QApplication::translate("FSC_MainWindow", "%", Q_NULLPTR));
        tbnVReverseIn2Close->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2002\345\205\263", Q_NULLPTR));
        label_21->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        radioButton_setFlowRate->setText(QApplication::translate("FSC_MainWindow", "\346\265\201\351\207\217\350\256\276\345\256\232", Q_NULLPTR));
        radioButton_setPWM->setText(QApplication::translate("FSC_MainWindow", "\345\215\240\347\251\272\346\257\224\350\256\276\345\256\232", Q_NULLPTR));
        tbnVOutOpen->setText(QApplication::translate("FSC_MainWindow", "\346\224\276\346\260\264\351\230\200\345\274\200", Q_NULLPTR));
        tbnPump1ReverseOff->setText(QApplication::translate("FSC_MainWindow", "1#\346\263\265\345\217\215\350\277\233\346\260\264\345\201\234\346\255\242", Q_NULLPTR));
        tbnPump1ReverseOn->setText(QApplication::translate("FSC_MainWindow", "1#\346\263\265\345\217\215\350\277\233\346\260\264\345\220\257\345\212\250", Q_NULLPTR));
        lineEdit_setFlowRate->setText(QApplication::translate("FSC_MainWindow", "0", Q_NULLPTR));
        tbnVForwardIn1Open->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2001\345\274\200", Q_NULLPTR));
        tbnPump2ReverseOn->setText(QApplication::translate("FSC_MainWindow", "2#\346\263\265\345\217\215\350\277\233\346\260\264\345\220\257\345\212\250", Q_NULLPTR));
        tbnPump2ForwardOn->setText(QApplication::translate("FSC_MainWindow", "2#\346\263\265\346\255\243\350\277\233\346\260\264\345\220\257\345\212\250", Q_NULLPTR));
        tbnPump2ForwardOff->setText(QApplication::translate("FSC_MainWindow", "2#\346\263\265\346\255\243\350\277\233\346\260\264\345\201\234\346\255\242", Q_NULLPTR));
        tbnPump2ReverseOff->setText(QApplication::translate("FSC_MainWindow", "2#\346\263\265\345\217\215\350\277\233\346\260\264\345\201\234\346\255\242", Q_NULLPTR));
        label_90->setText(QApplication::translate("FSC_MainWindow", "\345\236\213\345\217\267\357\274\232", Q_NULLPTR));
        labelplcState->setText(QApplication::translate("FSC_MainWindow", "TextLabel", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class FSC_MainWindow: public Ui_FSC_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FSC_MAINWINDOW_H
