/********************************************************************************
** Form generated from reading UI file 'fsc_mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FSC_MAINWINDOW_H
#define UI_FSC_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include <qcustomplot.h>

QT_BEGIN_NAMESPACE

class Ui_FSC_MainWindow
{
public:
    QWidget *centralwidget;
    QToolButton *tbnSysDevCheck;
    QLabel *label;
    QComboBox *comboBox_SensorTypeName;
    QWidget *layoutWidget_2;
    QGridLayout *gridLayout_28;
    QLineEdit *leFlowSpeed_SensorSpan;
    QLabel *label_14;
    QSpacerItem *verticalSpacer_53;
    QSpacerItem *verticalSpacer_54;
    QSpacerItem *horizontalSpacer_33;
    QLabel *lbC_2;
    QLabel *label_2;
    QCheckBox *checkBox_100SpanCal;
    QCheckBox *checkBox_100SpanCheck;
    QLabel *label_3;
    QCheckBox *checkBox_80SpanCal;
    QCheckBox *checkBox_80SpanCheck;
    QLabel *label_4;
    QCheckBox *checkBox_60SpanCal;
    QCheckBox *checkBox_60SpanCheck;
    QLabel *label_5;
    QCheckBox *checkBox_40SpanCal;
    QCheckBox *checkBox_40SpanCheck;
    QLabel *label_6;
    QCheckBox *checkBox_20SpanCal;
    QCheckBox *checkBox_20SpanCheck;
    QCheckBox *checkBox_10SpanCal;
    QCheckBox *checkBox_10SpanCheck;
    QLabel *label_7;
    QLabel *label_8;
    QCheckBox *checkBox_90SpanCal;
    QCheckBox *checkBox_90SpanCheck;
    QCheckBox *checkBox_70SpanCal;
    QCheckBox *checkBox_70SpanCheck;
    QLabel *label_9;
    QCheckBox *checkBox_50SpanCheck;
    QLabel *label_10;
    QCheckBox *checkBox_50SpanCal;
    QCheckBox *checkBox_30SpanCal;
    QCheckBox *checkBox_30SpanCheck;
    QLabel *label_11;
    QToolButton *tbnManualCheckDev;
    QToolButton *tbnCalStart;
    QFrame *line_4;
    QToolButton *tbnCalTermination;
    QTextBrowser *textBrow_calInfo;
    QLabel *label_16;
    QLineEdit *lineEdit_FM_1;
    QLineEdit *lineEdit_FM_2;
    QLineEdit *lineEdit_FM_4;
    QLineEdit *lineEdit_FM_3;
    QLineEdit *lineEdit_FM_6;
    QLineEdit *lineEdit_FM_5;
    QLineEdit *lineEdit_FM_8;
    QLineEdit *lineEdit_FM_7;
    QLineEdit *lineEdit_FM_11;
    QLineEdit *lineEdit_FM_10;
    QLineEdit *lineEdit_FM_12;
    QLineEdit *lineEdit_FM_9;
    QLineEdit *lineEdit_scale_show;
    QLineEdit *lineEdit_stdFM_sum;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *lineEdit_scale_flow;
    QLabel *label_19;
    QLabel *label_15;
    QLabel *label_22;
    QLineEdit *lineEdit_stdFM_flow;
    QLabel *label_23;
    QLabel *label_24;
    QCustomPlot *MyCustomPlot;
    QToolButton *tbnSensorType_5;
    QLineEdit *lineEdit_plotTime;
    QToolButton *tbnPoltClear;
    QGroupBox *groupBox;
    QComboBox *comboBox_PlotSenSel;
    QFrame *line_6;
    QCheckBox *checkBox_90SpanModify;
    QCheckBox *checkBox_80SpanModify;
    QCheckBox *checkBox_10SpanModify;
    QCheckBox *checkBox_40SpanModify;
    QCheckBox *checkBox_20SpanModify;
    QCheckBox *checkBox_60SpanModify;
    QCheckBox *checkBox_100SpanModify;
    QCheckBox *checkBox_70SpanModify;
    QCheckBox *checkBox_50SpanModify;
    QCheckBox *checkBox_30SpanModify;
    QLabel *label_25;
    QFrame *line;
    QFrame *line_5;
    QLabel *label_12;
    QFrame *line_7;
    QGroupBox *groupBox_2;
    QToolButton *tbnVOutOpen;
    QToolButton *tbnPumpForwardOn;
    QToolButton *tbnPumpReverseOn;
    QToolButton *tbnPumpForwardOff;
    QToolButton *tbnVOutClose;
    QToolButton *tbnPumpReverseOff;
    QToolButton *tbnVForwardIn2Open;
    QToolButton *tbnVForwardIn1Open;
    QToolButton *tbnVReverseIn1Open;
    QToolButton *tbnVReverseIn2Open;
    QToolButton *tbnVForwardIn2Close;
    QToolButton *tbnVForwardIn1Close;
    QToolButton *tbnVReverseIn1Close;
    QToolButton *tbnVReverseIn2Close;
    QLineEdit *lineEdit_setFlowRate;
    QLineEdit *lineEdit_setPWM;
    QRadioButton *radioButton_setFlowRate;
    QRadioButton *radioButton_setPWM;
    QLabel *label_21;
    QLabel *label_26;
    QLabel *label_13;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QFrame *line_2;
    QLabel *label_20;
    QLineEdit *lineEdit_FM_2_flow;
    QLineEdit *lineEdit_FM_10_flow;
    QLineEdit *lineEdit_FM_5_flow;
    QLineEdit *lineEdit_FM_3_flow;
    QLineEdit *lineEdit_FM_9_flow;
    QLineEdit *lineEdit_FM_8_flow;
    QLineEdit *lineEdit_FM_11_flow;
    QLineEdit *lineEdit_FM_12_flow;
    QLineEdit *lineEdit_FM_7_flow;
    QLineEdit *lineEdit_FM_6_flow;
    QLineEdit *lineEdit_FM_4_flow;
    QLineEdit *lineEdit_FM_1_flow;
    QToolButton *tbnScaleZero;
    QPushButton *pushButton;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_14;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_15;
    QPushButton *pushButton_13;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *FSC_MainWindow)
    {
        if (FSC_MainWindow->objectName().isEmpty())
            FSC_MainWindow->setObjectName(QStringLiteral("FSC_MainWindow"));
        FSC_MainWindow->resize(1801, 893);
        centralwidget = new QWidget(FSC_MainWindow);
        centralwidget->setObjectName(QStringLiteral("centralwidget"));
        tbnSysDevCheck = new QToolButton(centralwidget);
        tbnSysDevCheck->setObjectName(QStringLiteral("tbnSysDevCheck"));
        tbnSysDevCheck->setGeometry(QRect(44, 830, 121, 21));
        label = new QLabel(centralwidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(64, 70, 141, 16));
        comboBox_SensorTypeName = new QComboBox(centralwidget);
        comboBox_SensorTypeName->setObjectName(QStringLiteral("comboBox_SensorTypeName"));
        comboBox_SensorTypeName->setEnabled(true);
        comboBox_SensorTypeName->setGeometry(QRect(64, 90, 161, 22));
        layoutWidget_2 = new QWidget(centralwidget);
        layoutWidget_2->setObjectName(QStringLiteral("layoutWidget_2"));
        layoutWidget_2->setGeometry(QRect(64, 120, 161, 34));
        gridLayout_28 = new QGridLayout(layoutWidget_2);
        gridLayout_28->setObjectName(QStringLiteral("gridLayout_28"));
        gridLayout_28->setContentsMargins(0, 0, 0, 0);
        leFlowSpeed_SensorSpan = new QLineEdit(layoutWidget_2);
        leFlowSpeed_SensorSpan->setObjectName(QStringLiteral("leFlowSpeed_SensorSpan"));
        leFlowSpeed_SensorSpan->setEnabled(true);
        leFlowSpeed_SensorSpan->setReadOnly(true);

        gridLayout_28->addWidget(leFlowSpeed_SensorSpan, 1, 2, 1, 1);

        label_14 = new QLabel(layoutWidget_2);
        label_14->setObjectName(QStringLiteral("label_14"));

        gridLayout_28->addWidget(label_14, 1, 3, 1, 1);

        verticalSpacer_53 = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        gridLayout_28->addItem(verticalSpacer_53, 0, 2, 1, 1);

        verticalSpacer_54 = new QSpacerItem(20, 40, QSizePolicy::Minimum, QSizePolicy::Expanding);

        gridLayout_28->addItem(verticalSpacer_54, 2, 2, 1, 1);

        horizontalSpacer_33 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        gridLayout_28->addItem(horizontalSpacer_33, 1, 1, 1, 1);

        lbC_2 = new QLabel(layoutWidget_2);
        lbC_2->setObjectName(QStringLiteral("lbC_2"));

        gridLayout_28->addWidget(lbC_2, 1, 0, 1, 1);

        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(64, 198, 41, 16));
        checkBox_100SpanCal = new QCheckBox(centralwidget);
        checkBox_100SpanCal->setObjectName(QStringLiteral("checkBox_100SpanCal"));
        checkBox_100SpanCal->setEnabled(true);
        checkBox_100SpanCal->setGeometry(QRect(115, 198, 16, 16));
        checkBox_100SpanCal->setChecked(true);
        checkBox_100SpanCheck = new QCheckBox(centralwidget);
        checkBox_100SpanCheck->setObjectName(QStringLiteral("checkBox_100SpanCheck"));
        checkBox_100SpanCheck->setEnabled(true);
        checkBox_100SpanCheck->setGeometry(QRect(155, 331, 16, 16));
        checkBox_100SpanCheck->setChecked(true);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(64, 234, 41, 16));
        checkBox_80SpanCal = new QCheckBox(centralwidget);
        checkBox_80SpanCal->setObjectName(QStringLiteral("checkBox_80SpanCal"));
        checkBox_80SpanCal->setEnabled(true);
        checkBox_80SpanCal->setGeometry(QRect(115, 236, 16, 16));
        checkBox_80SpanCal->setChecked(false);
        checkBox_80SpanCheck = new QCheckBox(centralwidget);
        checkBox_80SpanCheck->setObjectName(QStringLiteral("checkBox_80SpanCheck"));
        checkBox_80SpanCheck->setEnabled(true);
        checkBox_80SpanCheck->setGeometry(QRect(155, 274, 16, 16));
        checkBox_80SpanCheck->setChecked(true);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(64, 270, 41, 16));
        checkBox_60SpanCal = new QCheckBox(centralwidget);
        checkBox_60SpanCal->setObjectName(QStringLiteral("checkBox_60SpanCal"));
        checkBox_60SpanCal->setEnabled(true);
        checkBox_60SpanCal->setGeometry(QRect(115, 274, 16, 16));
        checkBox_60SpanCal->setChecked(false);
        checkBox_60SpanCheck = new QCheckBox(centralwidget);
        checkBox_60SpanCheck->setObjectName(QStringLiteral("checkBox_60SpanCheck"));
        checkBox_60SpanCheck->setEnabled(true);
        checkBox_60SpanCheck->setGeometry(QRect(155, 293, 16, 16));
        checkBox_60SpanCheck->setChecked(true);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(64, 306, 41, 16));
        checkBox_40SpanCal = new QCheckBox(centralwidget);
        checkBox_40SpanCal->setObjectName(QStringLiteral("checkBox_40SpanCal"));
        checkBox_40SpanCal->setEnabled(true);
        checkBox_40SpanCal->setGeometry(QRect(115, 312, 16, 16));
        checkBox_40SpanCal->setChecked(false);
        checkBox_40SpanCheck = new QCheckBox(centralwidget);
        checkBox_40SpanCheck->setObjectName(QStringLiteral("checkBox_40SpanCheck"));
        checkBox_40SpanCheck->setEnabled(true);
        checkBox_40SpanCheck->setGeometry(QRect(155, 236, 16, 16));
        checkBox_40SpanCheck->setChecked(true);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(64, 342, 41, 16));
        checkBox_20SpanCal = new QCheckBox(centralwidget);
        checkBox_20SpanCal->setObjectName(QStringLiteral("checkBox_20SpanCal"));
        checkBox_20SpanCal->setEnabled(true);
        checkBox_20SpanCal->setGeometry(QRect(115, 350, 16, 16));
        checkBox_20SpanCal->setChecked(false);
        checkBox_20SpanCheck = new QCheckBox(centralwidget);
        checkBox_20SpanCheck->setObjectName(QStringLiteral("checkBox_20SpanCheck"));
        checkBox_20SpanCheck->setEnabled(true);
        checkBox_20SpanCheck->setGeometry(QRect(155, 369, 16, 16));
        checkBox_20SpanCheck->setChecked(true);
        checkBox_10SpanCal = new QCheckBox(centralwidget);
        checkBox_10SpanCal->setObjectName(QStringLiteral("checkBox_10SpanCal"));
        checkBox_10SpanCal->setEnabled(true);
        checkBox_10SpanCal->setGeometry(QRect(115, 369, 16, 16));
        checkBox_10SpanCal->setChecked(false);
        checkBox_10SpanCheck = new QCheckBox(centralwidget);
        checkBox_10SpanCheck->setObjectName(QStringLiteral("checkBox_10SpanCheck"));
        checkBox_10SpanCheck->setEnabled(true);
        checkBox_10SpanCheck->setGeometry(QRect(155, 312, 16, 16));
        checkBox_10SpanCheck->setChecked(true);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(64, 360, 41, 16));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(64, 216, 41, 16));
        checkBox_90SpanCal = new QCheckBox(centralwidget);
        checkBox_90SpanCal->setObjectName(QStringLiteral("checkBox_90SpanCal"));
        checkBox_90SpanCal->setEnabled(true);
        checkBox_90SpanCal->setGeometry(QRect(115, 217, 16, 16));
        checkBox_90SpanCal->setChecked(false);
        checkBox_90SpanCheck = new QCheckBox(centralwidget);
        checkBox_90SpanCheck->setObjectName(QStringLiteral("checkBox_90SpanCheck"));
        checkBox_90SpanCheck->setEnabled(true);
        checkBox_90SpanCheck->setGeometry(QRect(155, 198, 16, 16));
        checkBox_90SpanCheck->setChecked(false);
        checkBox_70SpanCal = new QCheckBox(centralwidget);
        checkBox_70SpanCal->setObjectName(QStringLiteral("checkBox_70SpanCal"));
        checkBox_70SpanCal->setEnabled(true);
        checkBox_70SpanCal->setGeometry(QRect(115, 255, 16, 16));
        checkBox_70SpanCal->setChecked(false);
        checkBox_70SpanCheck = new QCheckBox(centralwidget);
        checkBox_70SpanCheck->setObjectName(QStringLiteral("checkBox_70SpanCheck"));
        checkBox_70SpanCheck->setEnabled(true);
        checkBox_70SpanCheck->setGeometry(QRect(155, 255, 16, 16));
        checkBox_70SpanCheck->setChecked(false);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(64, 252, 41, 16));
        checkBox_50SpanCheck = new QCheckBox(centralwidget);
        checkBox_50SpanCheck->setObjectName(QStringLiteral("checkBox_50SpanCheck"));
        checkBox_50SpanCheck->setEnabled(true);
        checkBox_50SpanCheck->setGeometry(QRect(155, 350, 16, 16));
        checkBox_50SpanCheck->setChecked(false);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(64, 288, 41, 16));
        checkBox_50SpanCal = new QCheckBox(centralwidget);
        checkBox_50SpanCal->setObjectName(QStringLiteral("checkBox_50SpanCal"));
        checkBox_50SpanCal->setEnabled(true);
        checkBox_50SpanCal->setGeometry(QRect(115, 293, 16, 16));
        checkBox_50SpanCal->setChecked(false);
        checkBox_30SpanCal = new QCheckBox(centralwidget);
        checkBox_30SpanCal->setObjectName(QStringLiteral("checkBox_30SpanCal"));
        checkBox_30SpanCal->setEnabled(true);
        checkBox_30SpanCal->setGeometry(QRect(115, 331, 16, 16));
        checkBox_30SpanCal->setChecked(false);
        checkBox_30SpanCheck = new QCheckBox(centralwidget);
        checkBox_30SpanCheck->setObjectName(QStringLiteral("checkBox_30SpanCheck"));
        checkBox_30SpanCheck->setEnabled(true);
        checkBox_30SpanCheck->setGeometry(QRect(155, 217, 16, 16));
        checkBox_30SpanCheck->setChecked(false);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(64, 324, 41, 16));
        tbnManualCheckDev = new QToolButton(centralwidget);
        tbnManualCheckDev->setObjectName(QStringLiteral("tbnManualCheckDev"));
        tbnManualCheckDev->setGeometry(QRect(174, 830, 71, 21));
        tbnCalStart = new QToolButton(centralwidget);
        tbnCalStart->setObjectName(QStringLiteral("tbnCalStart"));
        tbnCalStart->setGeometry(QRect(312, 53, 51, 81));
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(274, 796, 1327, 90));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        tbnCalTermination = new QToolButton(centralwidget);
        tbnCalTermination->setObjectName(QStringLiteral("tbnCalTermination"));
        tbnCalTermination->setGeometry(QRect(1182, 53, 51, 81));
        textBrow_calInfo = new QTextBrowser(centralwidget);
        textBrow_calInfo->setObjectName(QStringLiteral("textBrow_calInfo"));
        textBrow_calInfo->setGeometry(QRect(372, 53, 801, 81));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(382, 218, 111, 16));
        lineEdit_FM_1 = new QLineEdit(centralwidget);
        lineEdit_FM_1->setObjectName(QStringLiteral("lineEdit_FM_1"));
        lineEdit_FM_1->setEnabled(false);
        lineEdit_FM_1->setGeometry(QRect(492, 218, 71, 20));
        lineEdit_FM_1->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_1->setReadOnly(true);
        lineEdit_FM_2 = new QLineEdit(centralwidget);
        lineEdit_FM_2->setObjectName(QStringLiteral("lineEdit_FM_2"));
        lineEdit_FM_2->setEnabled(true);
        lineEdit_FM_2->setGeometry(QRect(572, 218, 71, 20));
        lineEdit_FM_2->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_2->setReadOnly(true);
        lineEdit_FM_4 = new QLineEdit(centralwidget);
        lineEdit_FM_4->setObjectName(QStringLiteral("lineEdit_FM_4"));
        lineEdit_FM_4->setEnabled(true);
        lineEdit_FM_4->setGeometry(QRect(732, 218, 71, 20));
        lineEdit_FM_4->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_4->setReadOnly(true);
        lineEdit_FM_3 = new QLineEdit(centralwidget);
        lineEdit_FM_3->setObjectName(QStringLiteral("lineEdit_FM_3"));
        lineEdit_FM_3->setEnabled(true);
        lineEdit_FM_3->setGeometry(QRect(652, 218, 71, 20));
        lineEdit_FM_3->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_3->setReadOnly(true);
        lineEdit_FM_6 = new QLineEdit(centralwidget);
        lineEdit_FM_6->setObjectName(QStringLiteral("lineEdit_FM_6"));
        lineEdit_FM_6->setEnabled(true);
        lineEdit_FM_6->setGeometry(QRect(892, 218, 71, 20));
        lineEdit_FM_6->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_6->setReadOnly(true);
        lineEdit_FM_5 = new QLineEdit(centralwidget);
        lineEdit_FM_5->setObjectName(QStringLiteral("lineEdit_FM_5"));
        lineEdit_FM_5->setEnabled(true);
        lineEdit_FM_5->setGeometry(QRect(812, 218, 71, 20));
        lineEdit_FM_5->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_5->setReadOnly(true);
        lineEdit_FM_8 = new QLineEdit(centralwidget);
        lineEdit_FM_8->setObjectName(QStringLiteral("lineEdit_FM_8"));
        lineEdit_FM_8->setEnabled(true);
        lineEdit_FM_8->setGeometry(QRect(1094, 217, 71, 20));
        lineEdit_FM_8->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_8->setReadOnly(true);
        lineEdit_FM_7 = new QLineEdit(centralwidget);
        lineEdit_FM_7->setObjectName(QStringLiteral("lineEdit_FM_7"));
        lineEdit_FM_7->setEnabled(true);
        lineEdit_FM_7->setGeometry(QRect(1014, 217, 71, 20));
        lineEdit_FM_7->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_7->setReadOnly(true);
        lineEdit_FM_11 = new QLineEdit(centralwidget);
        lineEdit_FM_11->setObjectName(QStringLiteral("lineEdit_FM_11"));
        lineEdit_FM_11->setEnabled(true);
        lineEdit_FM_11->setGeometry(QRect(1334, 217, 71, 20));
        lineEdit_FM_11->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_11->setReadOnly(true);
        lineEdit_FM_10 = new QLineEdit(centralwidget);
        lineEdit_FM_10->setObjectName(QStringLiteral("lineEdit_FM_10"));
        lineEdit_FM_10->setEnabled(true);
        lineEdit_FM_10->setGeometry(QRect(1254, 217, 71, 20));
        lineEdit_FM_10->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_10->setReadOnly(true);
        lineEdit_FM_12 = new QLineEdit(centralwidget);
        lineEdit_FM_12->setObjectName(QStringLiteral("lineEdit_FM_12"));
        lineEdit_FM_12->setEnabled(true);
        lineEdit_FM_12->setGeometry(QRect(1414, 217, 71, 20));
        lineEdit_FM_12->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_12->setReadOnly(true);
        lineEdit_FM_9 = new QLineEdit(centralwidget);
        lineEdit_FM_9->setObjectName(QStringLiteral("lineEdit_FM_9"));
        lineEdit_FM_9->setEnabled(true);
        lineEdit_FM_9->setGeometry(QRect(1174, 217, 71, 20));
        lineEdit_FM_9->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_9->setReadOnly(true);
        lineEdit_scale_show = new QLineEdit(centralwidget);
        lineEdit_scale_show->setObjectName(QStringLiteral("lineEdit_scale_show"));
        lineEdit_scale_show->setEnabled(false);
        lineEdit_scale_show->setGeometry(QRect(482, 152, 101, 20));
        lineEdit_scale_show->setLayoutDirection(Qt::LeftToRight);
        lineEdit_scale_show->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_scale_show->setReadOnly(true);
        lineEdit_stdFM_sum = new QLineEdit(centralwidget);
        lineEdit_stdFM_sum->setObjectName(QStringLiteral("lineEdit_stdFM_sum"));
        lineEdit_stdFM_sum->setEnabled(false);
        lineEdit_stdFM_sum->setGeometry(QRect(482, 177, 101, 20));
        lineEdit_stdFM_sum->setLayoutDirection(Qt::LeftToRight);
        lineEdit_stdFM_sum->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_stdFM_sum->setReadOnly(true);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(652, 180, 101, 16));
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(382, 155, 61, 16));
        lineEdit_scale_flow = new QLineEdit(centralwidget);
        lineEdit_scale_flow->setObjectName(QStringLiteral("lineEdit_scale_flow"));
        lineEdit_scale_flow->setEnabled(false);
        lineEdit_scale_flow->setGeometry(QRect(752, 153, 101, 20));
        lineEdit_scale_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_scale_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_scale_flow->setReadOnly(true);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(652, 155, 81, 16));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(862, 153, 36, 20));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(862, 178, 36, 20));
        lineEdit_stdFM_flow = new QLineEdit(centralwidget);
        lineEdit_stdFM_flow->setObjectName(QStringLiteral("lineEdit_stdFM_flow"));
        lineEdit_stdFM_flow->setEnabled(false);
        lineEdit_stdFM_flow->setGeometry(QRect(752, 177, 101, 20));
        lineEdit_stdFM_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_stdFM_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_stdFM_flow->setReadOnly(true);
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(592, 178, 36, 20));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(382, 180, 121, 16));
        MyCustomPlot = new QCustomPlot(centralwidget);
        MyCustomPlot->setObjectName(QStringLiteral("MyCustomPlot"));
        MyCustomPlot->setGeometry(QRect(302, 290, 1271, 531));
        tbnSensorType_5 = new QToolButton(MyCustomPlot);
        tbnSensorType_5->setObjectName(QStringLiteral("tbnSensorType_5"));
        tbnSensorType_5->setGeometry(QRect(0, 510, 111, 21));
        lineEdit_plotTime = new QLineEdit(MyCustomPlot);
        lineEdit_plotTime->setObjectName(QStringLiteral("lineEdit_plotTime"));
        lineEdit_plotTime->setEnabled(true);
        lineEdit_plotTime->setGeometry(QRect(1110, 510, 51, 20));
        lineEdit_plotTime->setLayoutDirection(Qt::LeftToRight);
        lineEdit_plotTime->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_plotTime->setReadOnly(true);
        tbnPoltClear = new QToolButton(MyCustomPlot);
        tbnPoltClear->setObjectName(QStringLiteral("tbnPoltClear"));
        tbnPoltClear->setGeometry(QRect(1040, 510, 61, 21));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(292, 270, 1291, 561));
        comboBox_PlotSenSel = new QComboBox(centralwidget);
        comboBox_PlotSenSel->setObjectName(QStringLiteral("comboBox_PlotSenSel"));
        comboBox_PlotSenSel->setGeometry(QRect(1375, 265, 111, 22));
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(44, 420, 191, 16));
        line_6->setStyleSheet(QStringLiteral(""));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        checkBox_90SpanModify = new QCheckBox(centralwidget);
        checkBox_90SpanModify->setObjectName(QStringLiteral("checkBox_90SpanModify"));
        checkBox_90SpanModify->setEnabled(true);
        checkBox_90SpanModify->setGeometry(QRect(195, 217, 16, 16));
        checkBox_90SpanModify->setChecked(false);
        checkBox_80SpanModify = new QCheckBox(centralwidget);
        checkBox_80SpanModify->setObjectName(QStringLiteral("checkBox_80SpanModify"));
        checkBox_80SpanModify->setEnabled(true);
        checkBox_80SpanModify->setGeometry(QRect(195, 236, 16, 16));
        checkBox_80SpanModify->setChecked(false);
        checkBox_10SpanModify = new QCheckBox(centralwidget);
        checkBox_10SpanModify->setObjectName(QStringLiteral("checkBox_10SpanModify"));
        checkBox_10SpanModify->setEnabled(true);
        checkBox_10SpanModify->setGeometry(QRect(195, 369, 16, 16));
        checkBox_10SpanModify->setChecked(true);
        checkBox_40SpanModify = new QCheckBox(centralwidget);
        checkBox_40SpanModify->setObjectName(QStringLiteral("checkBox_40SpanModify"));
        checkBox_40SpanModify->setEnabled(true);
        checkBox_40SpanModify->setGeometry(QRect(195, 312, 16, 16));
        checkBox_40SpanModify->setChecked(false);
        checkBox_20SpanModify = new QCheckBox(centralwidget);
        checkBox_20SpanModify->setObjectName(QStringLiteral("checkBox_20SpanModify"));
        checkBox_20SpanModify->setEnabled(true);
        checkBox_20SpanModify->setGeometry(QRect(195, 350, 16, 16));
        checkBox_20SpanModify->setChecked(true);
        checkBox_60SpanModify = new QCheckBox(centralwidget);
        checkBox_60SpanModify->setObjectName(QStringLiteral("checkBox_60SpanModify"));
        checkBox_60SpanModify->setEnabled(true);
        checkBox_60SpanModify->setGeometry(QRect(195, 274, 16, 16));
        checkBox_60SpanModify->setChecked(false);
        checkBox_100SpanModify = new QCheckBox(centralwidget);
        checkBox_100SpanModify->setObjectName(QStringLiteral("checkBox_100SpanModify"));
        checkBox_100SpanModify->setEnabled(true);
        checkBox_100SpanModify->setGeometry(QRect(195, 198, 16, 16));
        checkBox_100SpanModify->setChecked(false);
        checkBox_70SpanModify = new QCheckBox(centralwidget);
        checkBox_70SpanModify->setObjectName(QStringLiteral("checkBox_70SpanModify"));
        checkBox_70SpanModify->setEnabled(true);
        checkBox_70SpanModify->setGeometry(QRect(195, 255, 16, 16));
        checkBox_70SpanModify->setChecked(false);
        checkBox_50SpanModify = new QCheckBox(centralwidget);
        checkBox_50SpanModify->setObjectName(QStringLiteral("checkBox_50SpanModify"));
        checkBox_50SpanModify->setEnabled(true);
        checkBox_50SpanModify->setGeometry(QRect(195, 293, 16, 16));
        checkBox_50SpanModify->setChecked(false);
        checkBox_30SpanModify = new QCheckBox(centralwidget);
        checkBox_30SpanModify->setObjectName(QStringLiteral("checkBox_30SpanModify"));
        checkBox_30SpanModify->setEnabled(true);
        checkBox_30SpanModify->setGeometry(QRect(195, 331, 16, 16));
        checkBox_30SpanModify->setChecked(false);
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(592, 153, 36, 20));
        line = new QFrame(centralwidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(265, 29, 20, 811));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(276, -10, 371, 80));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(672, 20, 141, 16));
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(742, -10, 861, 80));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(24, 30, 231, 811));
        tbnVOutOpen = new QToolButton(groupBox_2);
        tbnVOutOpen->setObjectName(QStringLiteral("tbnVOutOpen"));
        tbnVOutOpen->setGeometry(QRect(13, 450, 91, 21));
        tbnPumpForwardOn = new QToolButton(groupBox_2);
        tbnPumpForwardOn->setObjectName(QStringLiteral("tbnPumpForwardOn"));
        tbnPumpForwardOn->setGeometry(QRect(13, 700, 91, 21));
        tbnPumpReverseOn = new QToolButton(groupBox_2);
        tbnPumpReverseOn->setObjectName(QStringLiteral("tbnPumpReverseOn"));
        tbnPumpReverseOn->setGeometry(QRect(13, 730, 91, 21));
        tbnPumpForwardOff = new QToolButton(groupBox_2);
        tbnPumpForwardOff->setObjectName(QStringLiteral("tbnPumpForwardOff"));
        tbnPumpForwardOff->setGeometry(QRect(127, 700, 91, 21));
        tbnVOutClose = new QToolButton(groupBox_2);
        tbnVOutClose->setObjectName(QStringLiteral("tbnVOutClose"));
        tbnVOutClose->setGeometry(QRect(127, 450, 91, 21));
        tbnPumpReverseOff = new QToolButton(groupBox_2);
        tbnPumpReverseOff->setObjectName(QStringLiteral("tbnPumpReverseOff"));
        tbnPumpReverseOff->setGeometry(QRect(127, 730, 91, 21));
        tbnVForwardIn2Open = new QToolButton(groupBox_2);
        tbnVForwardIn2Open->setObjectName(QStringLiteral("tbnVForwardIn2Open"));
        tbnVForwardIn2Open->setGeometry(QRect(13, 510, 91, 21));
        tbnVForwardIn1Open = new QToolButton(groupBox_2);
        tbnVForwardIn1Open->setObjectName(QStringLiteral("tbnVForwardIn1Open"));
        tbnVForwardIn1Open->setGeometry(QRect(13, 480, 91, 21));
        tbnVReverseIn1Open = new QToolButton(groupBox_2);
        tbnVReverseIn1Open->setObjectName(QStringLiteral("tbnVReverseIn1Open"));
        tbnVReverseIn1Open->setGeometry(QRect(13, 540, 91, 21));
        tbnVReverseIn2Open = new QToolButton(groupBox_2);
        tbnVReverseIn2Open->setObjectName(QStringLiteral("tbnVReverseIn2Open"));
        tbnVReverseIn2Open->setGeometry(QRect(13, 570, 91, 21));
        tbnVForwardIn2Close = new QToolButton(groupBox_2);
        tbnVForwardIn2Close->setObjectName(QStringLiteral("tbnVForwardIn2Close"));
        tbnVForwardIn2Close->setGeometry(QRect(127, 510, 91, 21));
        tbnVForwardIn1Close = new QToolButton(groupBox_2);
        tbnVForwardIn1Close->setObjectName(QStringLiteral("tbnVForwardIn1Close"));
        tbnVForwardIn1Close->setGeometry(QRect(127, 480, 91, 21));
        tbnVReverseIn1Close = new QToolButton(groupBox_2);
        tbnVReverseIn1Close->setObjectName(QStringLiteral("tbnVReverseIn1Close"));
        tbnVReverseIn1Close->setGeometry(QRect(127, 540, 91, 21));
        tbnVReverseIn2Close = new QToolButton(groupBox_2);
        tbnVReverseIn2Close->setObjectName(QStringLiteral("tbnVReverseIn2Close"));
        tbnVReverseIn2Close->setGeometry(QRect(127, 570, 91, 21));
        lineEdit_setFlowRate = new QLineEdit(groupBox_2);
        lineEdit_setFlowRate->setObjectName(QStringLiteral("lineEdit_setFlowRate"));
        lineEdit_setFlowRate->setEnabled(true);
        lineEdit_setFlowRate->setGeometry(QRect(13, 630, 61, 20));
        lineEdit_setFlowRate->setLayoutDirection(Qt::LeftToRight);
        lineEdit_setFlowRate->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_setFlowRate->setReadOnly(false);
        lineEdit_setPWM = new QLineEdit(groupBox_2);
        lineEdit_setPWM->setObjectName(QStringLiteral("lineEdit_setPWM"));
        lineEdit_setPWM->setEnabled(true);
        lineEdit_setPWM->setGeometry(QRect(127, 630, 61, 20));
        lineEdit_setPWM->setLayoutDirection(Qt::LeftToRight);
        lineEdit_setPWM->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_setPWM->setReadOnly(false);
        radioButton_setFlowRate = new QRadioButton(groupBox_2);
        radioButton_setFlowRate->setObjectName(QStringLiteral("radioButton_setFlowRate"));
        radioButton_setFlowRate->setGeometry(QRect(13, 660, 89, 16));
        radioButton_setPWM = new QRadioButton(groupBox_2);
        radioButton_setPWM->setObjectName(QStringLiteral("radioButton_setPWM"));
        radioButton_setPWM->setGeometry(QRect(127, 660, 89, 16));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(78, 630, 36, 20));
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(192, 628, 36, 20));
        QFont font;
        font.setFamily(QStringLiteral("AcadEref"));
        font.setPointSize(12);
        label_26->setFont(font);
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(87, 150, 41, 16));
        label_29 = new QLabel(groupBox_2);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(126, 150, 41, 16));
        label_30 = new QLabel(groupBox_2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(168, 150, 41, 16));
        label_31 = new QLabel(groupBox_2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(40, 150, 41, 16));
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(1592, 29, 20, 812));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(382, 240, 111, 16));
        lineEdit_FM_2_flow = new QLineEdit(centralwidget);
        lineEdit_FM_2_flow->setObjectName(QStringLiteral("lineEdit_FM_2_flow"));
        lineEdit_FM_2_flow->setEnabled(true);
        lineEdit_FM_2_flow->setGeometry(QRect(572, 240, 71, 20));
        lineEdit_FM_2_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_2_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_2_flow->setReadOnly(true);
        lineEdit_FM_10_flow = new QLineEdit(centralwidget);
        lineEdit_FM_10_flow->setObjectName(QStringLiteral("lineEdit_FM_10_flow"));
        lineEdit_FM_10_flow->setEnabled(true);
        lineEdit_FM_10_flow->setGeometry(QRect(1254, 239, 71, 20));
        lineEdit_FM_10_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_10_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_10_flow->setReadOnly(true);
        lineEdit_FM_5_flow = new QLineEdit(centralwidget);
        lineEdit_FM_5_flow->setObjectName(QStringLiteral("lineEdit_FM_5_flow"));
        lineEdit_FM_5_flow->setEnabled(true);
        lineEdit_FM_5_flow->setGeometry(QRect(812, 240, 71, 20));
        lineEdit_FM_5_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_5_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_5_flow->setReadOnly(true);
        lineEdit_FM_3_flow = new QLineEdit(centralwidget);
        lineEdit_FM_3_flow->setObjectName(QStringLiteral("lineEdit_FM_3_flow"));
        lineEdit_FM_3_flow->setEnabled(true);
        lineEdit_FM_3_flow->setGeometry(QRect(652, 240, 71, 20));
        lineEdit_FM_3_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_3_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_3_flow->setReadOnly(true);
        lineEdit_FM_9_flow = new QLineEdit(centralwidget);
        lineEdit_FM_9_flow->setObjectName(QStringLiteral("lineEdit_FM_9_flow"));
        lineEdit_FM_9_flow->setEnabled(true);
        lineEdit_FM_9_flow->setGeometry(QRect(1174, 239, 71, 20));
        lineEdit_FM_9_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_9_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_9_flow->setReadOnly(true);
        lineEdit_FM_8_flow = new QLineEdit(centralwidget);
        lineEdit_FM_8_flow->setObjectName(QStringLiteral("lineEdit_FM_8_flow"));
        lineEdit_FM_8_flow->setEnabled(true);
        lineEdit_FM_8_flow->setGeometry(QRect(1094, 239, 71, 20));
        lineEdit_FM_8_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_8_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_8_flow->setReadOnly(true);
        lineEdit_FM_11_flow = new QLineEdit(centralwidget);
        lineEdit_FM_11_flow->setObjectName(QStringLiteral("lineEdit_FM_11_flow"));
        lineEdit_FM_11_flow->setEnabled(true);
        lineEdit_FM_11_flow->setGeometry(QRect(1334, 239, 71, 20));
        lineEdit_FM_11_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_11_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_11_flow->setReadOnly(true);
        lineEdit_FM_12_flow = new QLineEdit(centralwidget);
        lineEdit_FM_12_flow->setObjectName(QStringLiteral("lineEdit_FM_12_flow"));
        lineEdit_FM_12_flow->setEnabled(true);
        lineEdit_FM_12_flow->setGeometry(QRect(1414, 239, 71, 20));
        lineEdit_FM_12_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_12_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_12_flow->setReadOnly(true);
        lineEdit_FM_7_flow = new QLineEdit(centralwidget);
        lineEdit_FM_7_flow->setObjectName(QStringLiteral("lineEdit_FM_7_flow"));
        lineEdit_FM_7_flow->setEnabled(true);
        lineEdit_FM_7_flow->setGeometry(QRect(1014, 239, 71, 20));
        lineEdit_FM_7_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_7_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_7_flow->setReadOnly(true);
        lineEdit_FM_6_flow = new QLineEdit(centralwidget);
        lineEdit_FM_6_flow->setObjectName(QStringLiteral("lineEdit_FM_6_flow"));
        lineEdit_FM_6_flow->setEnabled(true);
        lineEdit_FM_6_flow->setGeometry(QRect(892, 240, 71, 20));
        lineEdit_FM_6_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_6_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_6_flow->setReadOnly(true);
        lineEdit_FM_4_flow = new QLineEdit(centralwidget);
        lineEdit_FM_4_flow->setObjectName(QStringLiteral("lineEdit_FM_4_flow"));
        lineEdit_FM_4_flow->setEnabled(true);
        lineEdit_FM_4_flow->setGeometry(QRect(732, 240, 71, 20));
        lineEdit_FM_4_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_4_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_4_flow->setReadOnly(true);
        lineEdit_FM_1_flow = new QLineEdit(centralwidget);
        lineEdit_FM_1_flow->setObjectName(QStringLiteral("lineEdit_FM_1_flow"));
        lineEdit_FM_1_flow->setEnabled(false);
        lineEdit_FM_1_flow->setGeometry(QRect(492, 240, 71, 20));
        lineEdit_FM_1_flow->setLayoutDirection(Qt::LeftToRight);
        lineEdit_FM_1_flow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_FM_1_flow->setReadOnly(true);
        tbnScaleZero = new QToolButton(centralwidget);
        tbnScaleZero->setObjectName(QStringLiteral("tbnScaleZero"));
        tbnScaleZero->setGeometry(QRect(920, 153, 91, 21));
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(630, 870, 75, 23));
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(1741, 84, 18, 16));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(1741, 113, 30, 16));
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(1741, 172, 16, 16));
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(1740, 230, 16, 16));
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(1740, 200, 16, 16));
        label_36 = new QLabel(centralwidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(1740, 260, 16, 16));
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(1740, 290, 16, 16));
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(1740, 310, 16, 16));
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(1740, 350, 16, 16));
        label_40 = new QLabel(centralwidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(1740, 380, 16, 16));
        label_41 = new QLabel(centralwidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(1740, 400, 16, 16));
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(1740, 430, 16, 16));
        label_43 = new QLabel(centralwidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(1740, 460, 16, 16));
        label_44 = new QLabel(centralwidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(1740, 490, 16, 16));
        layoutWidget = new QWidget(centralwidget);
        layoutWidget->setObjectName(QStringLiteral("layoutWidget"));
        layoutWidget->setGeometry(QRect(1660, 80, 77, 489));
        verticalLayout = new QVBoxLayout(layoutWidget);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        pushButton_2 = new QPushButton(layoutWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));

        verticalLayout->addWidget(pushButton_2);

        pushButton_3 = new QPushButton(layoutWidget);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));

        verticalLayout->addWidget(pushButton_3);

        pushButton_4 = new QPushButton(layoutWidget);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));

        verticalLayout->addWidget(pushButton_4);

        pushButton_5 = new QPushButton(layoutWidget);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));

        verticalLayout->addWidget(pushButton_5);

        pushButton_6 = new QPushButton(layoutWidget);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));

        verticalLayout->addWidget(pushButton_6);

        pushButton_7 = new QPushButton(layoutWidget);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));

        verticalLayout->addWidget(pushButton_7);

        pushButton_8 = new QPushButton(layoutWidget);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));

        verticalLayout->addWidget(pushButton_8);

        pushButton_9 = new QPushButton(layoutWidget);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));

        verticalLayout->addWidget(pushButton_9);

        pushButton_14 = new QPushButton(layoutWidget);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));

        verticalLayout->addWidget(pushButton_14);

        pushButton_10 = new QPushButton(layoutWidget);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));

        verticalLayout->addWidget(pushButton_10);

        pushButton_11 = new QPushButton(layoutWidget);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));

        verticalLayout->addWidget(pushButton_11);

        pushButton_12 = new QPushButton(layoutWidget);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));

        verticalLayout->addWidget(pushButton_12);

        pushButton_15 = new QPushButton(layoutWidget);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));

        verticalLayout->addWidget(pushButton_15);

        pushButton_13 = new QPushButton(layoutWidget);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));

        verticalLayout->addWidget(pushButton_13);

        pushButton_16 = new QPushButton(layoutWidget);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));

        verticalLayout->addWidget(pushButton_16);

        pushButton_17 = new QPushButton(layoutWidget);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));

        verticalLayout->addWidget(pushButton_17);

        pushButton_18 = new QPushButton(layoutWidget);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));

        verticalLayout->addWidget(pushButton_18);

        pushButton_19 = new QPushButton(centralwidget);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(1660, 780, 75, 23));
        FSC_MainWindow->setCentralWidget(centralwidget);
        layoutWidget->raise();
        groupBox_2->raise();
        line_4->raise();
        groupBox->raise();
        MyCustomPlot->raise();
        line_2->raise();
        line_7->raise();
        line_5->raise();
        tbnSysDevCheck->raise();
        label->raise();
        comboBox_SensorTypeName->raise();
        layoutWidget_2->raise();
        label_2->raise();
        checkBox_100SpanCal->raise();
        checkBox_100SpanCheck->raise();
        label_3->raise();
        checkBox_80SpanCal->raise();
        checkBox_80SpanCheck->raise();
        label_4->raise();
        checkBox_60SpanCal->raise();
        checkBox_60SpanCheck->raise();
        label_5->raise();
        checkBox_40SpanCal->raise();
        checkBox_40SpanCheck->raise();
        label_6->raise();
        checkBox_20SpanCal->raise();
        checkBox_20SpanCheck->raise();
        checkBox_10SpanCal->raise();
        checkBox_10SpanCheck->raise();
        label_7->raise();
        label_8->raise();
        checkBox_90SpanCal->raise();
        checkBox_90SpanCheck->raise();
        checkBox_70SpanCal->raise();
        checkBox_70SpanCheck->raise();
        label_9->raise();
        checkBox_50SpanCheck->raise();
        label_10->raise();
        checkBox_50SpanCal->raise();
        checkBox_30SpanCal->raise();
        checkBox_30SpanCheck->raise();
        label_11->raise();
        tbnManualCheckDev->raise();
        tbnCalStart->raise();
        tbnCalTermination->raise();
        textBrow_calInfo->raise();
        label_16->raise();
        lineEdit_FM_1->raise();
        lineEdit_FM_2->raise();
        lineEdit_FM_4->raise();
        lineEdit_FM_3->raise();
        lineEdit_FM_6->raise();
        lineEdit_FM_5->raise();
        lineEdit_FM_8->raise();
        lineEdit_FM_7->raise();
        lineEdit_FM_11->raise();
        lineEdit_FM_10->raise();
        lineEdit_FM_12->raise();
        lineEdit_FM_9->raise();
        lineEdit_scale_show->raise();
        lineEdit_stdFM_sum->raise();
        label_17->raise();
        label_18->raise();
        lineEdit_scale_flow->raise();
        label_19->raise();
        label_15->raise();
        label_22->raise();
        lineEdit_stdFM_flow->raise();
        label_23->raise();
        label_24->raise();
        comboBox_PlotSenSel->raise();
        line_6->raise();
        checkBox_90SpanModify->raise();
        checkBox_80SpanModify->raise();
        checkBox_10SpanModify->raise();
        checkBox_40SpanModify->raise();
        checkBox_20SpanModify->raise();
        checkBox_60SpanModify->raise();
        checkBox_100SpanModify->raise();
        checkBox_70SpanModify->raise();
        checkBox_50SpanModify->raise();
        checkBox_30SpanModify->raise();
        label_25->raise();
        line->raise();
        label_12->raise();
        label_20->raise();
        lineEdit_FM_2_flow->raise();
        lineEdit_FM_10_flow->raise();
        lineEdit_FM_5_flow->raise();
        lineEdit_FM_3_flow->raise();
        lineEdit_FM_9_flow->raise();
        lineEdit_FM_8_flow->raise();
        lineEdit_FM_11_flow->raise();
        lineEdit_FM_12_flow->raise();
        lineEdit_FM_7_flow->raise();
        lineEdit_FM_6_flow->raise();
        lineEdit_FM_4_flow->raise();
        lineEdit_FM_1_flow->raise();
        tbnScaleZero->raise();
        pushButton->raise();
        label_27->raise();
        label_28->raise();
        label_33->raise();
        label_34->raise();
        label_35->raise();
        label_36->raise();
        label_37->raise();
        label_38->raise();
        label_39->raise();
        label_40->raise();
        label_41->raise();
        label_42->raise();
        label_43->raise();
        label_44->raise();
        pushButton_19->raise();
        menubar = new QMenuBar(FSC_MainWindow);
        menubar->setObjectName(QStringLiteral("menubar"));
        menubar->setGeometry(QRect(0, 0, 1801, 23));
        FSC_MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(FSC_MainWindow);
        statusbar->setObjectName(QStringLiteral("statusbar"));
        FSC_MainWindow->setStatusBar(statusbar);
        QWidget::setTabOrder(tbnSysDevCheck, leFlowSpeed_SensorSpan);
        QWidget::setTabOrder(leFlowSpeed_SensorSpan, checkBox_100SpanCal);
        QWidget::setTabOrder(checkBox_100SpanCal, checkBox_100SpanCheck);
        QWidget::setTabOrder(checkBox_100SpanCheck, comboBox_SensorTypeName);
        QWidget::setTabOrder(comboBox_SensorTypeName, checkBox_80SpanCal);
        QWidget::setTabOrder(checkBox_80SpanCal, checkBox_80SpanCheck);
        QWidget::setTabOrder(checkBox_80SpanCheck, checkBox_60SpanCal);
        QWidget::setTabOrder(checkBox_60SpanCal, checkBox_60SpanCheck);
        QWidget::setTabOrder(checkBox_60SpanCheck, checkBox_40SpanCal);
        QWidget::setTabOrder(checkBox_40SpanCal, checkBox_40SpanCheck);
        QWidget::setTabOrder(checkBox_40SpanCheck, checkBox_20SpanCal);
        QWidget::setTabOrder(checkBox_20SpanCal, checkBox_20SpanCheck);
        QWidget::setTabOrder(checkBox_20SpanCheck, checkBox_10SpanCal);
        QWidget::setTabOrder(checkBox_10SpanCal, checkBox_10SpanCheck);
        QWidget::setTabOrder(checkBox_10SpanCheck, checkBox_90SpanCal);
        QWidget::setTabOrder(checkBox_90SpanCal, checkBox_90SpanCheck);
        QWidget::setTabOrder(checkBox_90SpanCheck, checkBox_70SpanCal);
        QWidget::setTabOrder(checkBox_70SpanCal, checkBox_70SpanCheck);
        QWidget::setTabOrder(checkBox_70SpanCheck, checkBox_50SpanCheck);
        QWidget::setTabOrder(checkBox_50SpanCheck, checkBox_50SpanCal);
        QWidget::setTabOrder(checkBox_50SpanCal, checkBox_30SpanCal);
        QWidget::setTabOrder(checkBox_30SpanCal, checkBox_30SpanCheck);
        QWidget::setTabOrder(checkBox_30SpanCheck, tbnManualCheckDev);
        QWidget::setTabOrder(tbnManualCheckDev, tbnCalStart);
        QWidget::setTabOrder(tbnCalStart, tbnCalTermination);
        QWidget::setTabOrder(tbnCalTermination, textBrow_calInfo);
        QWidget::setTabOrder(textBrow_calInfo, lineEdit_FM_1);
        QWidget::setTabOrder(lineEdit_FM_1, lineEdit_FM_2);
        QWidget::setTabOrder(lineEdit_FM_2, lineEdit_FM_4);
        QWidget::setTabOrder(lineEdit_FM_4, lineEdit_FM_3);
        QWidget::setTabOrder(lineEdit_FM_3, lineEdit_FM_6);
        QWidget::setTabOrder(lineEdit_FM_6, lineEdit_FM_5);
        QWidget::setTabOrder(lineEdit_FM_5, lineEdit_FM_8);
        QWidget::setTabOrder(lineEdit_FM_8, lineEdit_FM_7);
        QWidget::setTabOrder(lineEdit_FM_7, lineEdit_FM_11);
        QWidget::setTabOrder(lineEdit_FM_11, lineEdit_FM_10);
        QWidget::setTabOrder(lineEdit_FM_10, lineEdit_FM_12);
        QWidget::setTabOrder(lineEdit_FM_12, lineEdit_FM_9);
        QWidget::setTabOrder(lineEdit_FM_9, lineEdit_scale_show);
        QWidget::setTabOrder(lineEdit_scale_show, lineEdit_stdFM_sum);
        QWidget::setTabOrder(lineEdit_stdFM_sum, lineEdit_scale_flow);
        QWidget::setTabOrder(lineEdit_scale_flow, lineEdit_stdFM_flow);
        QWidget::setTabOrder(lineEdit_stdFM_flow, tbnSensorType_5);
        QWidget::setTabOrder(tbnSensorType_5, lineEdit_plotTime);
        QWidget::setTabOrder(lineEdit_plotTime, tbnPoltClear);
        QWidget::setTabOrder(tbnPoltClear, comboBox_PlotSenSel);
        QWidget::setTabOrder(comboBox_PlotSenSel, checkBox_90SpanModify);
        QWidget::setTabOrder(checkBox_90SpanModify, checkBox_80SpanModify);
        QWidget::setTabOrder(checkBox_80SpanModify, checkBox_10SpanModify);
        QWidget::setTabOrder(checkBox_10SpanModify, checkBox_40SpanModify);
        QWidget::setTabOrder(checkBox_40SpanModify, checkBox_20SpanModify);
        QWidget::setTabOrder(checkBox_20SpanModify, checkBox_60SpanModify);
        QWidget::setTabOrder(checkBox_60SpanModify, checkBox_100SpanModify);
        QWidget::setTabOrder(checkBox_100SpanModify, checkBox_70SpanModify);
        QWidget::setTabOrder(checkBox_70SpanModify, checkBox_50SpanModify);
        QWidget::setTabOrder(checkBox_50SpanModify, checkBox_30SpanModify);
        QWidget::setTabOrder(checkBox_30SpanModify, tbnVOutOpen);
        QWidget::setTabOrder(tbnVOutOpen, tbnPumpForwardOn);
        QWidget::setTabOrder(tbnPumpForwardOn, tbnPumpReverseOn);
        QWidget::setTabOrder(tbnPumpReverseOn, tbnPumpForwardOff);
        QWidget::setTabOrder(tbnPumpForwardOff, tbnVOutClose);
        QWidget::setTabOrder(tbnVOutClose, tbnPumpReverseOff);
        QWidget::setTabOrder(tbnPumpReverseOff, tbnVForwardIn2Open);
        QWidget::setTabOrder(tbnVForwardIn2Open, tbnVForwardIn1Open);
        QWidget::setTabOrder(tbnVForwardIn1Open, tbnVReverseIn1Open);
        QWidget::setTabOrder(tbnVReverseIn1Open, tbnVReverseIn2Open);
        QWidget::setTabOrder(tbnVReverseIn2Open, tbnVForwardIn2Close);
        QWidget::setTabOrder(tbnVForwardIn2Close, tbnVForwardIn1Close);
        QWidget::setTabOrder(tbnVForwardIn1Close, tbnVReverseIn1Close);
        QWidget::setTabOrder(tbnVReverseIn1Close, tbnVReverseIn2Close);
        QWidget::setTabOrder(tbnVReverseIn2Close, lineEdit_setFlowRate);
        QWidget::setTabOrder(lineEdit_setFlowRate, lineEdit_setPWM);
        QWidget::setTabOrder(lineEdit_setPWM, radioButton_setFlowRate);
        QWidget::setTabOrder(radioButton_setFlowRate, radioButton_setPWM);
        QWidget::setTabOrder(radioButton_setPWM, lineEdit_FM_2_flow);
        QWidget::setTabOrder(lineEdit_FM_2_flow, lineEdit_FM_10_flow);
        QWidget::setTabOrder(lineEdit_FM_10_flow, lineEdit_FM_5_flow);
        QWidget::setTabOrder(lineEdit_FM_5_flow, lineEdit_FM_3_flow);
        QWidget::setTabOrder(lineEdit_FM_3_flow, lineEdit_FM_9_flow);
        QWidget::setTabOrder(lineEdit_FM_9_flow, lineEdit_FM_8_flow);
        QWidget::setTabOrder(lineEdit_FM_8_flow, lineEdit_FM_11_flow);
        QWidget::setTabOrder(lineEdit_FM_11_flow, lineEdit_FM_12_flow);
        QWidget::setTabOrder(lineEdit_FM_12_flow, lineEdit_FM_7_flow);
        QWidget::setTabOrder(lineEdit_FM_7_flow, lineEdit_FM_6_flow);
        QWidget::setTabOrder(lineEdit_FM_6_flow, lineEdit_FM_4_flow);
        QWidget::setTabOrder(lineEdit_FM_4_flow, lineEdit_FM_1_flow);
        QWidget::setTabOrder(lineEdit_FM_1_flow, tbnScaleZero);
        QWidget::setTabOrder(tbnScaleZero, pushButton);
        QWidget::setTabOrder(pushButton, pushButton_2);
        QWidget::setTabOrder(pushButton_2, pushButton_3);
        QWidget::setTabOrder(pushButton_3, pushButton_4);
        QWidget::setTabOrder(pushButton_4, pushButton_5);
        QWidget::setTabOrder(pushButton_5, pushButton_6);
        QWidget::setTabOrder(pushButton_6, pushButton_7);
        QWidget::setTabOrder(pushButton_7, pushButton_8);
        QWidget::setTabOrder(pushButton_8, pushButton_9);
        QWidget::setTabOrder(pushButton_9, pushButton_10);
        QWidget::setTabOrder(pushButton_10, pushButton_11);
        QWidget::setTabOrder(pushButton_11, pushButton_12);
        QWidget::setTabOrder(pushButton_12, pushButton_13);
        QWidget::setTabOrder(pushButton_13, pushButton_14);
        QWidget::setTabOrder(pushButton_14, pushButton_15);
        QWidget::setTabOrder(pushButton_15, pushButton_16);
        QWidget::setTabOrder(pushButton_16, pushButton_17);
        QWidget::setTabOrder(pushButton_17, pushButton_18);

        retranslateUi(FSC_MainWindow);

        QMetaObject::connectSlotsByName(FSC_MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *FSC_MainWindow)
    {
        FSC_MainWindow->setWindowTitle(QApplication::translate("FSC_MainWindow", "\346\265\201\351\207\217\344\274\240\346\204\237\345\231\250\346\240\207\345\256\232\350\275\257\344\273\266", Q_NULLPTR));
        tbnSysDevCheck->setText(QApplication::translate("FSC_MainWindow", "\350\207\252\345\212\250\346\243\200\346\237\245\347\263\273\347\273\237\350\256\276\345\244\207", Q_NULLPTR));
        label->setText(QApplication::translate("FSC_MainWindow", "\351\200\211\346\213\251\345\276\205\346\240\207\345\256\232\344\274\240\346\204\237\345\231\250\345\236\213\345\217\267\357\274\232", Q_NULLPTR));
        label_14->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        lbC_2->setText(QApplication::translate("FSC_MainWindow", "\351\207\217\347\250\213\357\274\232", Q_NULLPTR));
        label_2->setText(QApplication::translate("FSC_MainWindow", "100%\357\274\232", Q_NULLPTR));
        checkBox_100SpanCal->setText(QString());
        checkBox_100SpanCheck->setText(QString());
        label_3->setText(QApplication::translate("FSC_MainWindow", "80%\357\274\232", Q_NULLPTR));
        checkBox_80SpanCal->setText(QString());
        checkBox_80SpanCheck->setText(QString());
        label_4->setText(QApplication::translate("FSC_MainWindow", "60%\357\274\232", Q_NULLPTR));
        checkBox_60SpanCal->setText(QString());
        checkBox_60SpanCheck->setText(QString());
        label_5->setText(QApplication::translate("FSC_MainWindow", "40%\357\274\232", Q_NULLPTR));
        checkBox_40SpanCal->setText(QString());
        checkBox_40SpanCheck->setText(QString());
        label_6->setText(QApplication::translate("FSC_MainWindow", "20%\357\274\232", Q_NULLPTR));
        checkBox_20SpanCal->setText(QString());
        checkBox_20SpanCheck->setText(QString());
        checkBox_10SpanCal->setText(QString());
        checkBox_10SpanCheck->setText(QString());
        label_7->setText(QApplication::translate("FSC_MainWindow", "10%\357\274\232", Q_NULLPTR));
        label_8->setText(QApplication::translate("FSC_MainWindow", "90%\357\274\232", Q_NULLPTR));
        checkBox_90SpanCal->setText(QString());
        checkBox_90SpanCheck->setText(QString());
        checkBox_70SpanCal->setText(QString());
        checkBox_70SpanCheck->setText(QString());
        label_9->setText(QApplication::translate("FSC_MainWindow", "70%\357\274\232", Q_NULLPTR));
        checkBox_50SpanCheck->setText(QString());
        label_10->setText(QApplication::translate("FSC_MainWindow", "50%\357\274\232", Q_NULLPTR));
        checkBox_50SpanCal->setText(QString());
        checkBox_30SpanCal->setText(QString());
        checkBox_30SpanCheck->setText(QString());
        label_11->setText(QApplication::translate("FSC_MainWindow", "30%\357\274\232", Q_NULLPTR));
        tbnManualCheckDev->setText(QApplication::translate("FSC_MainWindow", "\346\211\213\345\212\250\346\243\200\346\237\245", Q_NULLPTR));
        tbnCalStart->setText(QApplication::translate("FSC_MainWindow", "\345\274\200\345\247\213", Q_NULLPTR));
        tbnCalTermination->setText(QApplication::translate("FSC_MainWindow", "\347\273\210\346\255\242", Q_NULLPTR));
        textBrow_calInfo->setHtml(QApplication::translate("FSC_MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10:21:20 \345\220\257\345\212\250\346\240\207\345\256\232</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10:21:23 \346\211\223\345\274\200\350\277\233\346\260\264\351\230\200</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10:21:26 \346\211\223\345\274\200\346\260\264\346\263\265</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\""
                        ">...</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">....</p></body></html>", Q_NULLPTR));
        label_16->setText(QApplication::translate("FSC_MainWindow", "\345\276\205\346\240\207\345\256\232\344\274\240\346\204\237\345\231\250\347\264\257\350\256\241\357\274\232", Q_NULLPTR));
        lineEdit_FM_1->setText(QApplication::translate("FSC_MainWindow", "-22100.123", Q_NULLPTR));
        lineEdit_FM_2->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_4->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_3->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_6->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_5->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_8->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_7->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_11->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_10->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_12->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_9->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_scale_show->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_stdFM_sum->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        label_17->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\207\206\346\265\201\351\207\217\350\256\241\346\265\201\351\207\217\357\274\232", Q_NULLPTR));
        label_18->setText(QApplication::translate("FSC_MainWindow", "\345\244\251\345\271\263\346\230\276\347\244\272\357\274\232", Q_NULLPTR));
        lineEdit_scale_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        label_19->setText(QApplication::translate("FSC_MainWindow", "\345\244\251\345\271\263\350\256\241\347\256\227\346\265\201\351\200\237\357\274\232", Q_NULLPTR));
        label_15->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        label_22->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        lineEdit_stdFM_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        label_23->setText(QApplication::translate("FSC_MainWindow", "ml", Q_NULLPTR));
        label_24->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\207\206\346\265\201\351\207\217\350\256\241\347\264\257\350\256\241\357\274\232", Q_NULLPTR));
        tbnSensorType_5->setText(QApplication::translate("FSC_MainWindow", "\346\237\245\347\234\213\346\240\207\345\256\232\346\212\245\345\221\212", Q_NULLPTR));
        lineEdit_plotTime->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        tbnPoltClear->setText(QApplication::translate("FSC_MainWindow", "\346\270\205\347\251\272", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("FSC_MainWindow", "\345\217\230\345\214\226\346\233\262\347\272\277", Q_NULLPTR));
        comboBox_PlotSenSel->clear();
        comboBox_PlotSenSel->insertItems(0, QStringList()
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2501", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2502", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2503", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2504", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2505", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2506", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2507", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2508", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\2509", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\25010", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\25011", Q_NULLPTR)
         << QApplication::translate("FSC_MainWindow", "\344\274\240\346\204\237\345\231\25012", Q_NULLPTR)
        );
        checkBox_90SpanModify->setText(QString());
        checkBox_80SpanModify->setText(QString());
        checkBox_10SpanModify->setText(QString());
        checkBox_40SpanModify->setText(QString());
        checkBox_20SpanModify->setText(QString());
        checkBox_60SpanModify->setText(QString());
        checkBox_100SpanModify->setText(QString());
        checkBox_70SpanModify->setText(QString());
        checkBox_50SpanModify->setText(QString());
        checkBox_30SpanModify->setText(QString());
        label_25->setText(QApplication::translate("FSC_MainWindow", "ml", Q_NULLPTR));
        label_12->setText(QApplication::translate("FSC_MainWindow", "\350\207\252\345\212\250\346\240\207\345\256\232", Q_NULLPTR));
        groupBox_2->setTitle(QString());
        tbnVOutOpen->setText(QApplication::translate("FSC_MainWindow", "\346\224\276\346\260\264\351\230\200\345\274\200", Q_NULLPTR));
        tbnPumpForwardOn->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\345\220\257\345\212\250", Q_NULLPTR));
        tbnPumpReverseOn->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\345\220\257\345\212\250", Q_NULLPTR));
        tbnPumpForwardOff->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\345\201\234\346\255\242", Q_NULLPTR));
        tbnVOutClose->setText(QApplication::translate("FSC_MainWindow", "\346\224\276\346\260\264\351\230\200\345\205\263", Q_NULLPTR));
        tbnPumpReverseOff->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\345\201\234\346\255\242", Q_NULLPTR));
        tbnVForwardIn2Open->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2002\345\274\200", Q_NULLPTR));
        tbnVForwardIn1Open->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2001\345\274\200", Q_NULLPTR));
        tbnVReverseIn1Open->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2001\345\274\200", Q_NULLPTR));
        tbnVReverseIn2Open->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2002\345\274\200", Q_NULLPTR));
        tbnVForwardIn2Close->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2002\345\205\263", Q_NULLPTR));
        tbnVForwardIn1Close->setText(QApplication::translate("FSC_MainWindow", "\346\255\243\345\220\221\350\277\233\346\260\264\351\230\2001\345\205\263", Q_NULLPTR));
        tbnVReverseIn1Close->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2001\345\205\263", Q_NULLPTR));
        tbnVReverseIn2Close->setText(QApplication::translate("FSC_MainWindow", "\345\217\215\345\220\221\350\277\233\346\260\264\351\230\2002\345\205\263", Q_NULLPTR));
        lineEdit_setFlowRate->setText(QApplication::translate("FSC_MainWindow", "0", Q_NULLPTR));
        lineEdit_setPWM->setText(QApplication::translate("FSC_MainWindow", "0", Q_NULLPTR));
        radioButton_setFlowRate->setText(QApplication::translate("FSC_MainWindow", "\346\265\201\351\207\217\350\256\276\345\256\232", Q_NULLPTR));
        radioButton_setPWM->setText(QApplication::translate("FSC_MainWindow", "\345\215\240\347\251\272\346\257\224\350\256\276\345\256\232", Q_NULLPTR));
        label_21->setText(QApplication::translate("FSC_MainWindow", "ml/min", Q_NULLPTR));
        label_26->setText(QApplication::translate("FSC_MainWindow", "%", Q_NULLPTR));
        label_13->setText(QApplication::translate("FSC_MainWindow", "\346\240\207\345\256\232", Q_NULLPTR));
        label_29->setText(QApplication::translate("FSC_MainWindow", "\351\252\214\350\257\201", Q_NULLPTR));
        label_30->setText(QApplication::translate("FSC_MainWindow", "\344\277\256\346\255\243", Q_NULLPTR));
        label_31->setText(QApplication::translate("FSC_MainWindow", "\351\207\217\347\250\213", Q_NULLPTR));
        label_20->setText(QApplication::translate("FSC_MainWindow", "\345\276\205\346\240\207\345\256\232\344\274\240\346\204\237\345\231\250\346\265\201\351\207\217\357\274\232", Q_NULLPTR));
        lineEdit_FM_2_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_10_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_5_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_3_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_9_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_8_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_11_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_12_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_7_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_6_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_4_flow->setText(QApplication::translate("FSC_MainWindow", "0.1", Q_NULLPTR));
        lineEdit_FM_1_flow->setText(QApplication::translate("FSC_MainWindow", "-22100.123", Q_NULLPTR));
        tbnScaleZero->setText(QApplication::translate("FSC_MainWindow", "\345\216\273\347\232\256\346\270\205\351\233\266", Q_NULLPTR));
        pushButton->setText(QApplication::translate("FSC_MainWindow", "PushButton", Q_NULLPTR));
        label_27->setText(QApplication::translate("FSC_MainWindow", "plc", Q_NULLPTR));
        label_28->setText(QApplication::translate("FSC_MainWindow", "scale", Q_NULLPTR));
        label_33->setText(QApplication::translate("FSC_MainWindow", "1#", Q_NULLPTR));
        label_34->setText(QApplication::translate("FSC_MainWindow", "3#", Q_NULLPTR));
        label_35->setText(QApplication::translate("FSC_MainWindow", "2#", Q_NULLPTR));
        label_36->setText(QApplication::translate("FSC_MainWindow", "4#", Q_NULLPTR));
        label_37->setText(QApplication::translate("FSC_MainWindow", "5#", Q_NULLPTR));
        label_38->setText(QApplication::translate("FSC_MainWindow", "6#", Q_NULLPTR));
        label_39->setText(QApplication::translate("FSC_MainWindow", "7#", Q_NULLPTR));
        label_40->setText(QApplication::translate("FSC_MainWindow", "8#", Q_NULLPTR));
        label_41->setText(QApplication::translate("FSC_MainWindow", "9#", Q_NULLPTR));
        label_42->setText(QApplication::translate("FSC_MainWindow", "10#", Q_NULLPTR));
        label_43->setText(QApplication::translate("FSC_MainWindow", "11#", Q_NULLPTR));
        label_44->setText(QApplication::translate("FSC_MainWindow", "12#", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("FSC_MainWindow", "0", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("FSC_MainWindow", "1", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("FSC_MainWindow", "2", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("FSC_MainWindow", "3", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("FSC_MainWindow", "4", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("FSC_MainWindow", "5", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("FSC_MainWindow", "6", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("FSC_MainWindow", "7", Q_NULLPTR));
        pushButton_14->setText(QApplication::translate("FSC_MainWindow", "8", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("FSC_MainWindow", "9", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("FSC_MainWindow", "10", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("FSC_MainWindow", "11", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("FSC_MainWindow", "12", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("FSC_MainWindow", "13", Q_NULLPTR));
        pushButton_16->setText(QApplication::translate("FSC_MainWindow", "14", Q_NULLPTR));
        pushButton_17->setText(QApplication::translate("FSC_MainWindow", "15", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("FSC_MainWindow", "16", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("FSC_MainWindow", "PushButton", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class FSC_MainWindow: public Ui_FSC_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FSC_MAINWINDOW_H
